#!/usr/bin/env bash
# CM051 install.sh -- en-GB strings catalogue
# Generated 2026-05-19 as part of Rule 0.9
# (customer strings extractable from day one).
#
# Sourced by install.sh near the top, before any
# info/warn/step/ok/err/fail call. To add a new
# language: copy this file to install.sh.strings.<lang>.sh,
# translate the right-hand side of each MSG_* assignment,
# and invoke the installer with OSTLER_LANG=<lang>.
#
# Format-string entries use printf %s placeholders;
# install.sh wraps them in $(printf "$KEY" "$arg1" "$arg2").
# Translators: keep the same number of %s placeholders,
# in the same order, as the English source.

# ── Step (top-level phase) banners ──

MSG_STEP_CHECKING_PREREQUISITES="Checking prerequisites"
MSG_STEP_RUNNING_HEALTH_CHECK="Running health check"
MSG_STEP_SETUP_ANSWER_FEW_QUESTIONS_THEN_WALK="Setup (answer a few questions, then walk away)"

# ── Info messages (progress, context) ──

MSG_INFO_AND_RE_RUN_OSTLER_FDA="and re-run: ostler-fda"
MSG_INFO_APPLE_MAIL_ACCOUNTS_VISIBLE_INFORMATIONAL="Apple Mail accounts visible: %s (informational)"
MSG_INFO_APPLE_MAIL_DOES_NOT_APPEAR_HOLD="Apple Mail does not appear to hold any local messages yet. Doctor will surface a follow-up if no mail arrives within 24 hours."
MSG_INFO_APPLE_MAIL_HAS_CACHED_MESSAGES_INGEST="Apple Mail has cached messages. Ingest will pick them up on the next hourly tick."
MSG_INFO_APPLE_NOTARISATION_WILL_VERIFIED_GATEKEEPER_FIRST="Apple notarisation will be verified by Gatekeeper on first launch."
MSG_INFO_AVAILABLE_INSTALLER_WILL_SKIP_THIS_STEP="available the installer will skip this step automatically."
MSG_INFO_BASH_INSTALL_SNIPPET_SH="    bash %s/INSTALL_SNIPPET.sh"
MSG_INFO_BASH_INSTALL_SNIPPET_SH_2="  bash %s/INSTALL_SNIPPET.sh"
MSG_INFO_BETA_TESTERS_WITH_ACCESS_CAN_SET="Beta testers with access can set PWG_PIPELINE_REPO=<url> and re-run."
MSG_INFO_BETA_TESTERS_WITH_ACCESS_CAN_SET_2="Beta testers with access can set PWG_KNOWLEDGE_REPO=<url> and re-run."
MSG_INFO_BROWSER_EXTENSIONS_SKIPPED_NO_EXTENSIONS="Browser extensions skipped (--no-extensions)"
MSG_INFO_CD="  cd %s"
MSG_INFO_CLONED="  Cloned to %s."
MSG_INFO_CM042_INTEL_NOT_SUPPORTED_SKIPPING="Ostler RemoteCapture is Apple Silicon only. Skipping install on this machine."
MSG_INFO_CM042_LOGS_AT="RemoteCapture logs: %s/ostler-remotecapture.log (and .err)"
MSG_INFO_CM042_TCC_PRE_PROMPT="On first launch, Ostler RemoteCapture will ask macOS for Screen Recording and Microphone permission. Grant both so calls and meetings can be transcribed locally. No purple recording indicator appears in your menu bar – audio capture is silent by design."
MSG_INFO_CM048_PIPELINE_INSTALLED_VENV="  CM048 conversation pipeline installed in venv."
MSG_INFO_HUB_APP_VERIFYING="Verifying Ostler.app at %s"
MSG_INFO_HUB_APP_STAGING="Staging Ostler.app into /Applications from %s"
MSG_INFO_HUB_APP_DRAG_HINT="Open the installer DMG and drag both Ostler.app and OstlerInstaller.app onto the Applications shortcut, then re-run the installer."
MSG_OK_HUB_APP_PRESENT="Ostler.app already present at %s; signature verified."
MSG_OK_HUB_APP_STAGED="Ostler.app installed at %s"
MSG_WARN_HUB_APP_NOT_FOUND="Ostler.app was not found in /Applications and no bundled copy is available."
MSG_WARN_HUB_APP_VERIFY_FAILED="Ostler.app signature or notarisation verification failed. Leaving the bundle in place so support can inspect."
MSG_INFO_CLONING_DOCTOR_AGENT="Cloning Doctor agent..."
MSG_INFO_CLONING_EMAIL_INGEST_SCRIPTS="Cloning email-ingest scripts..."
MSG_INFO_CLONING_HUB_POWER_SCRIPTS="Cloning hub-power scripts..."
MSG_INFO_CLONING_IMPORT_PIPELINE="Cloning import pipeline..."
MSG_INFO_CLONING_WIKI_RECOMPILE_SCRIPTS="Cloning wiki-recompile scripts..."
MSG_INFO_COLIMA_INSTALLED_BUT_NOT_RUNNING_WILL="Colima installed but not running. Will start it."
MSG_INFO_COULD_NOT_EXPORT_CONTACTS_YOU_CAN="Could not export contacts. You can import manually later."
MSG_INFO_COULD_NOT_READ_CONTACT_CARD_NO="Could not read contact card. No problem – we will ask instead."
MSG_INFO_CP_R_TMP_DOCTOR_SRC_DOCTOR="  cp -R /tmp/doctor-src/doctor/agent/* %s/"
MSG_INFO_CREATING_PYTHON_VENV="  Creating Python venv at %s..."
MSG_INFO_CREATING_USER_FACING_CONTENT_TREE="Creating user-facing content tree at %s/"
MSG_INFO_CURL_FL_O_TMP_OSTLER_TGZ="  curl -fL -o /tmp/ostler.tgz %s"
MSG_INFO_DAILY_TICK_MANUAL_RUN_BASH_BIN="Daily tick. Manual run: bash %s/bin/wiki-recompile-tick.sh"
MSG_INFO_DESKTOP_HUB_NO_BATTERY_DETECTED_DISABLING="Desktop Hub (no battery) detected: disabling sleep system-wide"
MSG_INFO_DOCKER_COMPOSE_PROFILE_COMPILE_RUN_RM="  docker compose --profile compile run --rm wiki-compiler"
MSG_INFO_DOCKER_NOT_INSTALLED_WILL_INSTALL_COLIMA="Docker not installed. Will install Colima + Docker CLI + docker-compose plugin (lightweight, no Docker Desktop required)."
MSG_INFO_DOCTOR_AGENT_FILES_NOT_BUNDLED_WITH="Doctor agent files not bundled with installer."
MSG_INFO_EMAIL_INGEST_SCRIPTS_NOT_BUNDLED_WITH="Email-ingest scripts not bundled with installer."
MSG_FAIL_EMAIL_INGEST_VENDOR_MISSING_RE_RUN="Email-ingest scripts are missing from the installer bundle. Re-download the .app from ostler.ai/install and try again."
MSG_WARN_EMAIL_INGEST_SCRIPTS_NOT_BUNDLED_PLAINTEXT="Email-ingest scripts not bundled and --allow-plaintext was passed; LaunchAgent install will be skipped. Future emails will not be drained."
MSG_INFO_EXISTING_CHECKOUT_UPDATING="  Existing checkout at %s; updating..."
MSG_INFO_EXTRACTING_GMAIL_MBOX_FROM_TAKEOUT_ZIP="Extracting Gmail mbox from Takeout zip (this can take a minute for large archives)..."
MSG_INFO_FDA_EXTRACTION_MODULE_NOT_BUNDLED_SKIPPING="FDA extraction module not bundled. Skipping instant data extraction."
MSG_INFO_FOUND_GMAIL_MBOX_MB="Found Gmail mbox at %s (%s MB)"
MSG_INFO_FOUND_GOOGLE_TAKEOUT_ZIP_MB="Found Google Takeout zip at %s (%s MB)"
MSG_INFO_FULL_DISK_ACCESS_DETECTED_FULL_EXTRACTION="Full Disk Access detected – full extraction available."
MSG_INFO_GDPR_EXPORTS_DETECTED_BUT_IMPORT_PIPELINE="GDPR exports detected but import pipeline not yet available."
MSG_INFO_GDPR_EXPORT_IMPORT_WILL_AVAILABLE_WHEN="GDPR-export import will be available when the pipeline ships."
MSG_INFO_GIT_CLONE="  git clone %s %s"
MSG_INFO_GIT_CLONE_2="  git clone %s %s"
MSG_INFO_GIT_CLONE_TMP_DOCTOR_SRC="  git clone %s /tmp/doctor-src"
MSG_INFO_GIT_CLONE_TMP_HUB_POWER_SRC="  git clone %s /tmp/hub-power-src"
MSG_INFO_GIT_CLONE_TMP_HUB_SRC="  git clone %s /tmp/hub-src"
MSG_INFO_GIT_NOT_FOUND_INSTALLING_XCODE_COMMAND="Git not found. Installing Xcode Command Line Tools..."
MSG_INFO_HOURLY_TICK_FIRST_RUN_CLAMPED_LAST="Hourly tick. First run clamped to last 90 days."
MSG_INFO_HUB_POWER_AC_ONLY_HUB_SKIPPING_LAUNCHAGENT="AC-only hub (no battery detected), skipping hub-power LaunchAgent."
MSG_INFO_HUB_POWER_SCRIPTS_NOT_BUNDLED_WITH="Hub power scripts not bundled with installer."
MSG_INFO_IF_TAILSCALE_WINDOW_APPEARS_SIGN_WITH="If a Tailscale window appears, sign in with Apple / Google / Microsoft."
MSG_INFO_IMPORT_EVERNOTE_UI_DOCTOR_WILL_SURFACE="Import-Evernote UI in Doctor will surface a 'service unavailable'"
MSG_INFO_IMPORT_PIPELINE_NOT_BUNDLED_WITH_INSTALLER="Import pipeline not bundled with installer."
MSG_INFO_INSTALLING_CM042="Installing Ostler RemoteCapture v%s (call + meeting transcription)..."
MSG_INFO_INSTALLING_CM048_PIPELINE_FROM="Installing CM048 conversation pipeline from %s..."
MSG_INFO_INSTALLING_CM048_PIPELINE_INTO_VENV="  Installing CM048 pipeline into venv..."
MSG_INFO_INSTALLING_COLIMA_DOCKER_CLI="Installing Colima + Docker CLI..."
MSG_INFO_INSTALLING_HOMEBREW="Installing Homebrew..."
MSG_INFO_INSTALLING_KNOWLEDGE_SERVICE_FROM="Installing Knowledge service from %s..."
MSG_INFO_INSTALLING_OLLAMA="Installing Ollama..."
MSG_INFO_INSTALLING_OSTLER_KNOWLEDGE_INTO_VENV="  Installing ostler-knowledge into venv..."
MSG_INFO_INSTALLING_SAFARI_EXTENSION_APPLICATIONS="Installing Safari extension to /Applications"
MSG_INFO_INSTALLING_SECURITY_PYTHON_DEPENDENCIES="Installing security Python dependencies..."
MSG_INFO_INSTALLING_SQLCIPHER="Installing SQLCipher..."
MSG_INFO_INSTALLING_TAILSCALE="Installing Tailscale..."
MSG_INFO_INTEL_SUPPORT_NOT_ROADMAP_RAISE_REQUEST="Intel support is not on the roadmap; raise a request if required."
MSG_INFO_KNOWLEDGE_SERVICE_BUNDLED_WITH_INSTALLER="Knowledge service bundled with installer; using vendored source."
MSG_INFO_KNOWLEDGE_SERVICE_NOT_INSTALLED_PWG_KNOWLEDGE="Knowledge service not installed: PWG_KNOWLEDGE_REPO empty."
MSG_INFO_LATER_SYSTEM_SETTINGS_PRIVACY_SECURITY_FULL="later in System Settings > Privacy & Security > Full Disk Access"
MSG_INFO_LAUNCH_VERIFY_CRON_DELIVERY_IMESSAGE_TCC="  launch to verify cron-delivery + imessage-tcc posture)."
MSG_INFO_LICENCE_APACHE_2_0_FULL_TEXT="Licence: %s is Apache 2.0. Full text: %s/LICENSES/Apache-2.0.txt"
MSG_INFO_LICENCE_CHECK_UPSTREAM_TERMS_BEFORE_COMMERCIAL="Licence: %s – check upstream terms before commercial use."
MSG_INFO_LOCAL_STORE_GOOGLE_NEVER_SEES_THAT="local store – Google never sees that Ostler exists."
MSG_INFO_LOGS_EMAIL_INGEST_LOG_ERR="Logs: %s/email-ingest.log (and .err)"
MSG_INFO_LOGS_OSTLER_ASSISTANT_LOG_ERR="Logs: %s/ostler-assistant.log (and .err)"
MSG_INFO_LOGS_WIKI_RECOMPILE_LOG_ERR="Logs: %s/wiki-recompile.log (and .err)"
MSG_INFO_MACBOOK_HUBS_SET_PWG_HUB_POWER="MacBook hubs: set PWG_HUB_POWER_REPO=<url> and re-run."
MSG_INFO_MACBOOK_HUB_DETECTED_SETTING_NEVER_SLEEP="MacBook Hub detected: setting never-sleep on AC only (hub-power handles battery transitions)"
MSG_INFO_MAC_MINI_STUDIO_DEPLOYMENTS_ARE_UNAFFECTED="Mac Mini / Studio deployments are unaffected (always-on AC)."
MSG_INFO_MAC_SIDE_DATA_IMESSAGE_SAFARI_ETC="Mac-side data (iMessage, Safari, etc.) was extracted above."
MSG_INFO_MANUAL_RESTART_LAUNCHCTL_KICKSTART_K_GUI="Manual restart: launchctl kickstart -k gui/\$(id -u)/com.creativemachines.ostler.assistant"
MSG_INFO_MANUAL_RUN_BASH_BIN_EMAIL_INGEST="Manual run: bash %s/bin/email-ingest-tick.sh"
MSG_INFO_MESSAGE_WHEN_FEATURE_FLAG_LATER_FLIPPED="message when the feature flag is later flipped on."
MSG_INFO_NEED_HELP_EMAIL_SUPPORT_OSTLER_AI="Need help? Email support@ostler.ai. We aim to reply within 2 working days."
MSG_INFO_MKDIR_P_CP_R_TMP_HUB="  mkdir -p %s && cp -R /tmp/hub-power-src/hub-power/* %s/"
MSG_INFO_MKDIR_P_CP_R_TMP_HUB_2="  mkdir -p %s && cp -R /tmp/hub-src/email-ingest/* %s/"
MSG_INFO_NO_CHANNELS_CONFIGURED_RUN_LATER_BIN="No channels configured. Run later: %s/bin/ostler-assistant setup channels --interactive"
MSG_INFO_NO_FDA_SOURCES_AVAILABLE_RIGHT_NOW="No FDA sources available right now. You can grant Full Disk Access"
MSG_INFO_NO_GDPR_EXPORTS_FOUND_DOWNLOADS_DESKTOP="No GDPR exports found in Downloads, Desktop, or Documents."
MSG_INFO_OPENING_CHROME_WEB_STORE="Opening Chrome Web Store: %s"
MSG_INFO_OSTLER_ASSISTANT_BINARY_NOT_INSTALLED_SKIPPING="ostler-assistant binary not installed; skipping doctor probe"
MSG_INFO_OSTLER_ASSISTANT_DOCTOR_DEFERRED_DAEMON_MAY="ostler-assistant doctor: deferred (daemon may still be"
MSG_INFO_OSTLER_INSTALL_ROOT_BASH_INSTALL_SNIPPET="  OSTLER_INSTALL_ROOT=%s bash %s/INSTALL_SNIPPET.sh"
MSG_INFO_OSTLER_INSTALL_ROOT_OSTLER_DIR_LOGS="  OSTLER_INSTALL_ROOT=%s OSTLER_DIR=%s LOGS_DIR=%s \\\\"
MSG_INFO_OSTLER_KNOWLEDGE_INSTALLED_VENV="  ostler-knowledge installed in venv."
MSG_INFO_OSTLER_WILL_SHOW_EXTRA_CONSENT_SCREEN="      Ostler will show an extra consent screen before installing"
MSG_INFO_OVERRIDE_SOURCE_REPO_WITH_PWG_CM048="  Override the source repo with PWG_CM048_REPO=<url> ./install.sh"
MSG_INFO_OVERRIDE_SOURCE_REPO_WITH_PWG_DOCTOR="  Override the source repo with PWG_DOCTOR_REPO=<url> ./install.sh"
MSG_INFO_OVERRIDE_SOURCE_REPO_WITH_PWG_HUB="  Override the source repo with PWG_HUB_POWER_REPO=<url> ./install.sh"
MSG_INFO_OVERRIDE_SOURCE_REPO_WITH_PWG_KNOWLEDGE="  Override the source repo with PWG_KNOWLEDGE_REPO=<url> ./install.sh"
MSG_INFO_OVERRIDE_SOURCE_REPO_WITH_PWG_PIPELINE="  Override the source repo with PWG_PIPELINE_REPO=<url> ./install.sh"
MSG_INFO_PERSISTING_CONSENT_RECORDS_REGION="Persisting consent records and region..."
MSG_INFO_PHASE_3_BATTERY_WATCHER_ARMED_PID="Phase 3 battery watcher armed (PID %s)"
MSG_INFO_POLICY_OVERRIDE_EDIT_OSTLER_POWER_CONF="Policy override: edit ~/.ostler/power.conf (normal / aggressive / eco)"
MSG_INFO_PROBING_IMESSAGE_AUTOMATION_PERMISSION_READ_ONLY="Probing iMessage Automation permission (read-only)..."
MSG_INFO_PULLING_NOMIC_EMBED_TEXT_274_MB="Pulling nomic-embed-text (274 MB)..."
MSG_INFO_PULLING_THIS_MAY_TAKE_FEW_MINUTES="Pulling %s (%s)... this may take a few minutes."
MSG_INFO_QUARANTINE_XATTR_CLEARED_ONCE_DEVELOPER_ID="Quarantine xattr cleared. Once the Developer-ID build is"
MSG_INFO_READING_SAFARI_IMESSAGE_NOTES_CALENDAR_PHOTOS="Reading Safari, iMessage, Notes, Calendar, Photos, Reminders, Mail..."
MSG_INFO_READING_YOUR_CONTACT_CARD_PRE_FILL="Reading your contact card to pre-fill your details..."
MSG_INFO_REGION_EU_EEA_SOURCE="Region: EU/EEA (%s, source: %s)"
MSG_INFO_REGION_SOURCE="Region: %s (source: %s)"
MSG_INFO_REGION_UNITED_KINGDOM_SOURCE="Region: United Kingdom (source: %s)"
MSG_INFO_REGION_UNITED_STATES_SOURCE="Region: United States (source: %s)"
MSG_INFO_REPO_URL="Repo URL: %s"
MSG_INFO_REPO_URL_2="Repo URL: %s"
MSG_INFO_REPO_URL_3="Repo URL: %s"
MSG_INFO_RECOVERY_PASSPHRASE_INTRO="One more (optional) safeguard: a recovery passphrase you choose. It's a second way back in if Touch ID ever fails."
MSG_INFO_RECOVERY_PASSPHRASE_SKIPPED_BIP39_ONLY="Recovery passphrase skipped. Your 12-word recovery phrase remains the only fallback if Touch ID fails."
MSG_INFO_REUSING_EXISTING_DOCTOR_AGENT_INSTALL="Reusing existing Doctor agent install at %s"
MSG_INFO_REUSING_EXISTING_EMAIL_INGEST_INSTALL="Reusing existing email-ingest install at %s"
MSG_INFO_REUSING_EXISTING_HUB_POWER_INSTALL="Reusing existing hub-power install at %s"
MSG_INFO_REUSING_EXISTING_JWT_SECRET="Reusing existing JWT_SECRET in %s"
MSG_INFO_REUSING_EXISTING_PWG_SERVICE_TOKEN="Reusing existing PWG service token at %s"
MSG_INFO_REUSING_EXISTING_WIKI_RECOMPILE_INSTALL="Reusing existing wiki-recompile install at %s"
MSG_INFO_SAFARI_EXTENSION_BUNDLE_NOT_PRESENT_THIS="Safari extension bundle not present in this installer build (skipping)"
MSG_INFO_SCANNING_GDPR_DATA_EXPORTS="Scanning for GDPR data exports..."
MSG_INFO_SET_PWG_DOCTOR_REPO_URL_RE="Set PWG_DOCTOR_REPO=<url> and re-run to install."
MSG_INFO_SET_PWG_HUB_POWER_REPO_HR015="Set PWG_HUB_POWER_REPO=<HR015 url> and re-run to install."
MSG_INFO_SKIPPED_CONVERSATION_MODEL_PULL_LATER_OLLAMA="Skipped conversation model. Pull later: ollama pull %s"
MSG_INFO_STARTING_COLIMA_LIGHTWEIGHT_DOCKER_RUNTIME="Starting Colima (lightweight Docker runtime)..."
MSG_INFO_STARTING_DOCKER_DESKTOP="Starting Docker Desktop..."
MSG_INFO_STARTING_OLLAMA="Starting Ollama..."
MSG_INFO_STARTING_RUN_OSTLER_ASSISTANT_DOCTOR_AFTER="  starting; run \`ostler-assistant doctor\` after first"
MSG_INFO_SYMLINKING="  Symlinking %s -> %s"
MSG_INFO_SYSTEM_SETTINGS_INTERNET_ACCOUNTS_OSTLER_READS="(System Settings > Internet Accounts). Ostler reads from Mail's"
MSG_INFO_TAR_XZF_TMP_OSTLER_TGZ_C="  tar xzf /tmp/ostler.tgz -C %s/bin"
MSG_INFO_THE_REST_OSTLER_RUNS_WITHOUT_DOCTOR="(The rest of Ostler runs without the Doctor dashboard.)"
MSG_INFO_THIS_EXPECTED_NOW_GDPR_IMPORT_WILL="This is expected for now. GDPR import will be available in a future update."
MSG_INFO_THIS_MAY_TAKE_5_15_MINUTES="This may take 5-15 minutes depending on how much data you have..."
MSG_INFO_THIS_READS_MACOS_DATABASES_DIRECTLY_NO="This reads macOS databases directly – no export needed."
MSG_INFO_TIP_INCLUDE_YOUR_GMAIL_ADD_IT="Tip: to include your Gmail, add it to Mac Mail first"
MSG_INFO_TO_INSTALL_LATER_ONCE_YOU_HAVE="To install later once you have access:"
MSG_INFO_TRIGGERING_ICLOUD_SYNC_SILENT_FIRST_RUN="Triggering iCloud sync for %s (silent, first-run only)..."
MSG_INFO_UK_GDPR_ARTICLE_9_REQUIRED_SPECIAL="      (UK GDPR Article 9 - required for special-category data)."
MSG_INFO_UPDATING_EXISTING_PIPELINE="Updating existing pipeline..."
MSG_INFO_USER_FACING_TREE_ALREADY_ANNOUNCED_SENTINEL="User-facing tree already announced (sentinel present); skipping"
MSG_INFO_VANE_NOT_RESPONDING_OPTIONAL_SEE_PHASE="Vane not responding (optional; see Phase 3.8b warnings)"
MSG_INFO_VIEW_ANY_TIME_WITH_BASH_INSTALL="View any time with: bash install.sh --licenses"
MSG_INFO_VOICE_RECOGNITION_WILL_STAY_OFF_YOU="Voice recognition will stay off. You can enable later in Settings."
MSG_INFO_WAITING_YOU_SIGN_TAILSCALE_UP_3="Waiting for you to sign in to Tailscale (up to 3 minutes)..."
MSG_INFO_WHATSAPP_CONNECTOR_LEFT_OFF_YOU_CAN="WhatsApp connector left off. You can enable it later via Settings."
MSG_INFO_WHATSAPP_KEEPALIVE_SCHEDULED_08_50_17="WhatsApp keepalive scheduled at 08:50 + 17:50 (label com.creativemachines.ostler.whatsapp-keepalive)"
MSG_INFO_WIKI_RECOMPILE_SCRIPTS_NOT_BUNDLED_WITH="Wiki-recompile scripts not bundled with installer."
MSG_INFO_WIKI_WILL_NOT_AUTO_UPDATE_YOU="Wiki will not auto-update; you can re-run the first-compile manually:"
MSG_INFO_WROTE_POSTURE_MARKER_INSTALL_JSON="Wrote posture marker: %s/install.json"
MSG_INFO_YOUR_EXPORTS_ARE_SAFE_IMPORT_THEM="Your exports are safe. Import them later with: ostler-import %s"
MSG_INFO_YOUR_MAC_DATA_IMESSAGE_SAFARI_ETC="Your Mac data (iMessage, Safari, etc.) was already extracted above."
MSG_INFO_YOU_CAN_ADD_IT_LATER_INSTANT="You can add it later for instant onboarding from Safari, iMessage, etc."

# ── Success messages ──

MSG_OK_AI_MODEL_SELECTED_YOUR_GB_RAM="AI model: %s (%s) – selected for your %s GB RAM"
MSG_OK_ALL_SOURCES_SELECTED_FACE_RECOGNITION_STILL="All sources selected (face recognition still off)"
MSG_OK_ALREADY_AVAILABLE="%s already available"
MSG_OK_APPLE_SILICON_DETECTED="Apple Silicon detected"
MSG_OK_APPS_LAUNCHED_TRIGGER_ICLOUD_SYNC="Apps launched to trigger iCloud sync"
MSG_OK_APP_DATABASES_ALREADY_PRESENT_SKIPPING_PRE="App databases already present (skipping pre-launch)"
MSG_OK_ASSISTANT_CONFIG_SAVED_MODE_0600="Assistant config saved to %s (mode 0600)"
MSG_OK_BACKED_UP_CONTACTS="Backed up %s contacts to %s"
MSG_OK_CM042_INSTALLED="Ostler RemoteCapture v%s installed at %s"
MSG_OK_CM042_LAUNCHAGENT_LOADED="Ostler RemoteCapture LaunchAgent loaded (label %s)"
MSG_OK_COLIMA_DOCKER_CLI_INSTALLED="Colima and Docker CLI installed"
MSG_OK_COLIMA_WILL_START_AUTOMATICALLY_BOOT="Colima will start automatically on boot"
MSG_OK_CONFIG_SAVED_ENV="Config saved to %s/.env"
MSG_OK_CONSENT_RECORDS_REGION_PERSISTED_OSTLER_POSTURE="Consent records and region persisted to ~/.ostler/posture/"
MSG_OK_DATABASES_ENCRYPTED_TOUCH_ID_REQUIRED_EACH_STARTUP="Databases encrypted. Touch ID required at each startup."
MSG_OK_DEFERRED_DEVICE_REGISTRATION_RETRY_INSTALLED_RUNS="Deferred device-registration retry installed (runs hourly until queue clears)"
MSG_OK_DOCKER_RUNNING="Docker running"
MSG_OK_DOCKER_RUNNING_TOOK_S="Docker running (took %ss)"
MSG_OK_DOCTOR_AGENT_CLONED_FROM="Doctor agent cloned from %s"
MSG_OK_DOCTOR_AGENT_FILES_BUNDLED_WITH_INSTALLER="Doctor agent files bundled with installer"
MSG_OK_DOCTOR_DEPENDENCIES_INSTALLED="Doctor dependencies installed"
MSG_OK_EMAIL_CHANNEL_FOLDER="Email channel: %s (folder: %s)"
MSG_OK_EMAIL_INGEST_LAUNCHAGENT_LOADED_LABEL_COM="Email-ingest LaunchAgent loaded (label com.creativemachines.ostler.email-ingest)"
MSG_OK_EMAIL_INGEST_SCRIPTS_BUNDLED_WITH_INSTALLER="Email-ingest scripts bundled with installer"
MSG_OK_EMAIL_INGEST_SCRIPTS_CLONED_FROM="Email-ingest scripts cloned from %s"
MSG_OK_EMBEDDING_MODEL_READY="Embedding model ready"
MSG_OK_EXPORTED_CONTACTS_WILL_IMPORT_AUTOMATICALLY="Exported %s contacts (will import automatically)"
MSG_OK_EXPORT_WATCHER_INSTALLED_SCANS_DOWNLOADS_EVERY="Export watcher installed (scans Downloads every 4 hours)"
MSG_OK_EXTRACTED="Extracted to %s"
MSG_OK_EXTRACTED_FROM_SOURCE_S_DATA_SAVED="Extracted from %s source(s). Data saved to %s/imports/fda/"
MSG_OK_FDA_RE_RUN_SCHEDULED_12_HOURS="FDA re-run scheduled for ~12 hours from now (catches slow iCloud syncs)"
MSG_OK_FOUND="Found: %s"
MSG_OK_FOUND_EXPORTS="Found exports at %s"
MSG_OK_FOUND_GDPR_EXPORT_S="Found %s GDPR export(s):"
MSG_OK_GB_FREE_DISK_SPACE="%s GB free disk space"
MSG_OK_GB_RAM_DETECTED="%s GB RAM detected"
MSG_OK_GDPR_IMPORT_COMPLETE="GDPR import complete"
MSG_OK_GIT_AVAILABLE="Git available"
MSG_OK_HOMEBREW_INSTALLED="Homebrew installed"
MSG_OK_HUB_POWER_LAUNCHAGENT_LOADED_LABEL_COM="Hub power LaunchAgent loaded (label com.creativemachines.ostler.hub-power)"
MSG_OK_HUB_POWER_SCRIPTS_BUNDLED_WITH_INSTALLER="Hub power scripts bundled with installer"
MSG_OK_HUB_POWER_SCRIPTS_CLONED_FROM="Hub power scripts cloned from %s"
MSG_OK_IMESSAGE_AUTOMATION_PERMISSION_GRANTED="iMessage Automation permission: granted"
MSG_OK_IMESSAGE_CHANNEL="iMessage channel: %s"
MSG_OK_IMPORT_PIPELINE_BUNDLED_WITH_INSTALLER="Import pipeline bundled with installer"
MSG_OK_IMPORT_PIPELINE_READY="Import pipeline ready"
MSG_OK_CM048_PIPELINE_READY="CM048 conversation pipeline ready."
MSG_OK_KNOWLEDGE_SERVICE_READY="Knowledge service ready: %s"
MSG_OK_LICENCE_TEXTS_INSTALLED_SOURCE="Licence texts installed at %s/ (source: %s)"
MSG_OK_MACOS_DETECTED="macOS %s detected"
MSG_OK_NOMIC_EMBED_TEXT_ALREADY_AVAILABLE="nomic-embed-text already available"
MSG_OK_OLLAMA_HEALTHY="Ollama healthy"
MSG_OK_OLLAMA_INSTALLED="Ollama installed"
MSG_OK_OLLAMA_INSTALLED_CLI_ONLY_MAY_NEED="Ollama installed (CLI only – may need manual start after reboot)"
MSG_OK_OLLAMA_INSTALLED_DESKTOP_APP="Ollama installed (desktop app)"
MSG_OK_OLLAMA_RUNNING="Ollama running"
MSG_OK_OSTLER_ASSISTANT_DOCTOR_NO_ERRORS_DETECTED="ostler-assistant doctor: no errors detected"
MSG_OK_OSTLER_ASSISTANT_LAUNCHAGENT_LOADED_LABEL_COM="Ostler assistant LaunchAgent loaded (label com.creativemachines.ostler.assistant)"
MSG_OK_OSTLER_ASSISTANT_V_STAGED_SIGNED="ostler-assistant v%s staged at %s (signed)"
MSG_OK_OSTLER_ASSISTANT_V_STAGED_UNSIGNED="ostler-assistant v%s staged at %s (unsigned)"
MSG_OK_OSTLER_DOCTOR_RUNNING_HTTP_LOCALHOST_8089="Ostler Doctor running at http://localhost:8089/doctor"
MSG_OK_OSTLER_IMPORT_OSTLER_FDA_OSTLER_UNINSTALL="ostler-import, ostler-fda, and ostler-uninstall commands installed"
MSG_OK_OXIGRAPH_HEALTHY="Oxigraph healthy"
MSG_OK_RECOVERY_PASSPHRASE_CAPTURED_FOR_PHASE_3="Recovery passphrase noted. It will be set up during Phase 3."
MSG_OK_RECOVERY_PASSPHRASE_CONFIGURED="Recovery passphrase configured."
MSG_OK_TOUCH_ID_BRIEFING_ACKNOWLEDGED="Touch ID briefing acknowledged."
MSG_OK_POWER_SOURCE_AC_DESKTOP_MAC_NO="Power source: AC (desktop Mac, no battery)"
MSG_OK_POWER_SOURCE_AC_GOOD_10_15="Power source: AC (good for the 10-15 minute install)"
MSG_OK_PREVIOUS_INSTALLATION_DETECTED_LOADING_CONFIG="Previous installation detected. Loading config..."
MSG_OK_PYTHON="Python %s"
MSG_OK_PYTHON_INSTALLED="Python %s installed"
MSG_OK_QDRANT_HEALTHY="Qdrant healthy"
MSG_OK_READY="%s ready"
MSG_OK_RECOMMENDED_SOURCES_SELECTED="Recommended sources selected"
MSG_OK_RECOVERY_KEY_SAVED_KEYCHAIN_SEARCH_OSTLER="Recovery key saved to Keychain (search 'Ostler' in Passwords app)"
MSG_OK_REDIS_HEALTHY="Redis healthy"
MSG_OK_SAFARI_EXTENSION_INSTALLED="Safari extension installed at %s"
MSG_OK_SECURITY_ALREADY_CONFIGURED_PREVIOUS_RUN="Security already configured on a previous run."
MSG_OK_SECURITY_MODULE_INSTALLED_INTO_VENV="Security module installed into venv"
MSG_OK_SEEDED_FRESH_JWT_SECRET="Seeded fresh JWT_SECRET in %s"
MSG_OK_SEEDED_PWG_SERVICE_TOKEN="Seeded PWG service token at %s"
MSG_OK_SERVICES_STARTED_QDRANT_6333_OXIGRAPH_7878="Services started (Qdrant :6333, Oxigraph :7878, Redis :6379)"
MSG_OK_SLEEP_DISABLED_AC_BATTERY_SLEEP_PRESERVED="Sleep disabled on AC, battery sleep preserved, wake-on-network enabled"
MSG_OK_SLEEP_DISABLED_WAKE_NETWORK_ENABLED="Sleep disabled, wake-on-network enabled"
MSG_OK_TAILSCALE_ALREADY_INSTALLED="Tailscale already installed"
MSG_OK_TAILSCALE_INSTALLED="Tailscale installed"
MSG_OK_TAILSCALE_IP="Tailscale IP: %s"
MSG_OK_THIRD_PARTY_ATTRIBUTIONS_INSTALLED_SOURCE="Third-party attributions installed (source: %s)"
MSG_OK_USER_FACING_TREE_READY="User-facing tree ready"
MSG_OK_USING_OSTLER_FOLDER_LABEL_INSTEAD="Using 'Ostler' folder/label instead."
MSG_OK_VANE_HEALTHY_LOCAL_WEB_SEARCH="Vane healthy (local web search)"
MSG_OK_VANE_RUNNING_HTTP_LOCALHOST_3000_TALKS="Vane running at http://localhost:3000 (talks to your local Ollama)"
MSG_OK_WHATSAPP_CONNECTOR_WILL_ENABLED_CONSENT_RECORDED="WhatsApp connector will be enabled (consent recorded)"
MSG_OK_WIKI_RECOMPILE_LAUNCHAGENT_LOADED_LABEL_COM="Wiki-recompile LaunchAgent loaded (label com.creativemachines.ostler.wiki-recompile)"
MSG_OK_WIKI_RECOMPILE_SCRIPTS_BUNDLED_WITH_INSTALLER="Wiki-recompile scripts bundled with installer"
MSG_OK_WIKI_RECOMPILE_SCRIPTS_CLONED_FROM="Wiki-recompile scripts cloned from %s"
MSG_OK_WIKI_RUNNING_HTTP_LOCALHOST_8044="Wiki running at http://localhost:8044"
MSG_OK_YOUR_ASSISTANT_CALLED="Your assistant is called %s"

# ── Warnings (non-fatal) ──

MSG_WARN_BASH_INSTALL_SNIPPET_SH="  bash %s/INSTALL_SNIPPET.sh"
MSG_WARN_BLOCK_3_1_CM024_PRODUCTISATION_STACK="Block 3.1 of the CM024 productisation stack adds pyproject.toml --"
MSG_WARN_BUNDLE="  Bundle: %s"
MSG_WARN_CD="  cd %s"
MSG_WARN_CD_2="    cd %s"
MSG_WARN_CM042_APPLE_SILICON_ONLY="Ostler RemoteCapture v%s is Apple Silicon only (detected: %s)."
MSG_WARN_CM042_DOWNLOAD_FAILED="Could not download Ostler RemoteCapture v%s from %s"
MSG_WARN_CM042_DOWNLOAD_NEXT_STEPS="Common causes: release tag not yet published, network offline, or upstream notarisation still in flight. Re-run the installer once the release is live."
MSG_WARN_CM042_EXTRACT_FAILED="Could not extract Ostler RemoteCapture tarball; skipping LaunchAgent."
MSG_WARN_CM042_LAUNCHAGENT_LOAD_FAILED="Ostler RemoteCapture LaunchAgent load failed. See output above and ~/Library/LaunchAgents/."
MSG_WARN_CM048_PIPELINE_CONVERSATION_ENRICHMENT_UNAVAILABLE="  Conversation enrichment will not be available. The rest of Ostler installs normally; re-run without --allow-plaintext to wire CM048 in."
MSG_WARN_CM048_PIPELINE_INSTALL_FAILED_CLONE="CM048 pipeline install failed (clone)."
MSG_WARN_CM048_PIPELINE_LOOKED_FOR_PATH="  Looked for: %s/cm048_pipeline/pyproject.toml"
MSG_WARN_CM048_PIPELINE_MISSING_FROM_APP_BUNDLE="  This usually means the installer .app was built without"
MSG_WARN_CM048_PIPELINE_MISSING_FROM_APP_BUNDLE_2="  the vendored cm048_pipeline package bundled into"
MSG_WARN_CM048_PIPELINE_MISSING_FROM_APP_BUNDLE_3="  Contents/Resources/. Re-download the installer or"
MSG_WARN_CM048_PIPELINE_MISSING_FROM_APP_BUNDLE_4="  re-run with --allow-plaintext for a dev/CI install."
MSG_WARN_CM048_PIPELINE_NOT_FOUND="CM048 conversation pipeline not found. Conversation enrichment cannot run without it."
MSG_WARN_CM048_PIPELINE_SKIPPED_ALLOW_PLAINTEXT="CM048 conversation pipeline setup skipped (--allow-plaintext)."
MSG_WARN_CM048_REPO_RESOLVED_BUT_PYPROJECT_TOML="CM048 source resolved but pyproject.toml is missing; venv setup skipped."
MSG_WARN_COLIMA_FAILED_START_TRYING_DOCKER_DESKTOP="Colima failed to start. Trying Docker Desktop as fallback..."
MSG_WARN_COMMON_CAUSES_TAG_V_NOT_YET="Common causes: tag v%s not yet published, network offline,"
MSG_WARN_CONSENT_CLI_STDERR_FIRST_400_CHARS="  consent_cli stderr (first 400 chars):"
MSG_WARN_CONSOLE_SCRIPT_NOT_CREATED_PYPROJECT_TOML="  Console script not created at %s; pyproject.toml may be missing the [project.scripts] entry."
MSG_WARN_CONTINUING_BECAUSE_ALLOW_PLAINTEXT_WAS_PASSED="Continuing because --allow-plaintext was passed."
MSG_WARN_CONTINUING_INSTALL_RE_RUN_OSTLER_FDA="Continuing install. Re-run \`ostler-fda\` after diagnosing the error above."
MSG_WARN_CONTINUING_WITHOUT_CONTACT_CARD_AUTO_FILL="Continuing without contact-card auto-fill – Ostler will ask you instead."
MSG_WARN_CONVERSATIONS_SENT_IMESSAGE_WILL_SILENTLY_FAIL="  Conversations sent to iMessage will silently fail until"
MSG_WARN_COULD_NOT_CHANGE_SLEEP_SETTINGS_ENABLE="Could not change sleep settings. Enable 'Prevent automatic sleeping when plugged in' in System Settings > Energy."
MSG_WARN_COULD_NOT_CHANGE_SLEEP_SETTINGS_ENABLE_2="Could not change sleep settings. Enable 'Prevent automatic sleeping' in System Settings > Energy."
MSG_WARN_COULD_NOT_DOWNLOAD_OSTLER_ASSISTANT_V="Could not download ostler-assistant v%s from %s"
MSG_WARN_COULD_NOT_EXTRACT_GMAIL_MBOX_FROM="Could not extract Gmail mbox from the Takeout zip – skipping."
MSG_WARN_COULD_NOT_EXTRACT_OSTLER_ASSISTANT_TARBALL="Could not extract ostler-assistant tarball; skipping LaunchAgent."
MSG_WARN_COULD_NOT_FIND_TAILSCALE_CLI_YOU="Could not find the Tailscale CLI. You can configure it manually later."
MSG_WARN_COULD_NOT_INSTALL_LEGAL_CONSENT_STRINGS="Could not install legal/ consent-strings package; continuing"
MSG_WARN_COULD_NOT_INSTALL_LICENSES_DIRECTORY_NON="Could not install LICENSES/ directory (non-fatal)."
MSG_WARN_COULD_NOT_INSTALL_OSTLER_SECURITY_INTO="Could not install ostler_security into the Hub venv."
MSG_WARN_COULD_NOT_INSTALL_THIRD_PARTY_NOTICES="Could not install THIRD_PARTY_NOTICES.md (non-fatal)."
MSG_WARN_COULD_NOT_OBTAIN_DOCTOR_AGENT_BUNDLED="Could not obtain Doctor agent (bundled / cloned both failed)."
MSG_WARN_DOCTOR_NOT_BUNDLED_HARD_FAIL="Ostler Doctor files not found. Required for the iOS pairing flow (Ostler.app iframes :8089/pair-ios)."
MSG_WARN_DOCTOR_LOOKED_FOR_PATH="  Looked for: %s/doctor/agent/"
MSG_WARN_DOCTOR_MISSING_FROM_APP_BUNDLE="  This usually means the installer .app was built without"
MSG_WARN_DOCTOR_MISSING_FROM_APP_BUNDLE_2="  the vendored doctor/agent/ source bundled into"
MSG_WARN_DOCTOR_MISSING_FROM_APP_BUNDLE_3="  Contents/Resources/. Re-download the installer or"
MSG_WARN_DOCTOR_MISSING_FROM_APP_BUNDLE_4="  re-run with --allow-plaintext for a dev/CI install."
MSG_FAIL_DOCTOR_INSTALL_REQUIRED="Doctor install aborted: required for the iOS pairing flow. Re-download the installer or pass --allow-plaintext for a dev/CI install."
MSG_WARN_COULD_NOT_OBTAIN_EMAIL_INGEST_SCRIPTS="Could not obtain email-ingest scripts (bundled / cloned both failed)."
MSG_WARN_COULD_NOT_OBTAIN_HUB_POWER_SCRIPTS="Could not obtain hub-power scripts (bundled / cloned both failed)."
MSG_WARN_COULD_NOT_OBTAIN_WIKI_RECOMPILE_SCRIPTS="Could not obtain wiki-recompile scripts (bundled / cloned both failed)."
MSG_WARN_COULD_NOT_OPEN_CHROME_WEB_STORE="Could not open Chrome Web Store URL automatically: %s"
MSG_WARN_COULD_NOT_PERSIST_REGION_JSON_CONTINUING="Could not persist region.json (continuing - Doctor will surface)"
MSG_WARN_COULD_NOT_SAVE_KEYCHAIN_PLEASE_WRITE="Could not save to Keychain. Please write it down."
MSG_WARN_COULD_NOT_START_OLLAMA_AUTOMATICALLY="Could not start Ollama automatically."
MSG_WARN_COULD_NOT_UPDATE_PIPELINE_OFFLINE="Could not update pipeline (offline?)"
MSG_WARN_COULD_NOT_WRITE_PIPELINE_SIGNALS_JSON="Could not write pipeline_signals.json. The Doctor empty-Mail diagnostic will fall back to safe defaults until the next install or tick."
MSG_WARN_CURL_SAID="Curl said:"
MSG_WARN_DIRECTORY_NOT_FOUND_SKIPPING_IMPORT="Directory not found: %s – skipping import."
MSG_WARN_DOCKER_COMPOSE_F_DOCKER_COMPOSE_YML="       docker compose -f %s/docker-compose.yml restart vane"
MSG_WARN_DOCKER_COMPOSE_PROFILE_COMPILE_RUN_RM="  docker compose --profile compile run --rm wiki-compiler"
MSG_WARN_DOCKER_COMPOSE_PROFILE_COMPILE_RUN_RM_2="    docker compose --profile compile run --rm wiki-compiler"
MSG_WARN_DOCKER_COMPOSE_UP_D_WIKI_SITE="    docker compose up -d wiki-site"
MSG_WARN_DOCKER_DID_NOT_START_WITHIN_SECONDS="Docker did not start within %s seconds."
MSG_WARN_DOCKER_INSTALLED_BUT_NOT_RUNNING_WILL="Docker installed but not running. Will need to start it."
MSG_WARN_DOCKER_OLLAMA_MID_INSTALL_HANG_READINESS="Docker / Ollama mid-install and hang the readiness probes."
MSG_WARN_EARLY_MARKERS_CHANNELS_STILL_CONNECTING_APPLE="  early markers (channels still connecting + Apple"
MSG_WARN_EMAIL_INGEST_LAUNCHAGENT_INSTALL_FAILED_SEE="Email-ingest LaunchAgent install failed. See output above."
MSG_WARN_ENCRYPTION_PASSPHRASE_VALIDATION_WILL_NOT_WORK="Encryption will not work."
MSG_WARN_ENCRYPTION_PASSPHRASE_VALIDATION_WILL_NOT_WORK_2="Encryption will not work, and"
MSG_WARN_ENSURE_PINNED_PWG_KNOWLEDGE_REPO_TAG="ensure the pinned PWG_KNOWLEDGE_REPO tag includes it."
MSG_WARN_EVENTS_PERMISSION_MESSAGES_APP="  Events permission for Messages.app)."
MSG_WARN_FDA_EXTRACTOR_EXITED_NON_ZERO_LAST="FDA extractor exited non-zero (%s). Last 20 lines of output:"
MSG_WARN_FDA_MODULE_NOT_BUNDLED_LINE_1="FDA extraction module not bundled into this installer."
MSG_WARN_FDA_MODULE_NOT_BUNDLED_LINE_2="Expected at: Contents/Resources/ostler_fda/ (inside the .app)."
MSG_WARN_FDA_MODULE_NOT_BUNDLED_LINE_3="Most likely cause: a build regression dropped the vendor copy. Re-download the .app from ostler.ai/install."
MSG_WARN_FDA_MODULE_NOT_BUNDLED_PLAINTEXT="FDA extraction module not bundled. Continuing because --allow-plaintext was passed – instant data extraction will be skipped."
MSG_WARN_FILEVAULT_NOT_ENABLED="FileVault is NOT enabled."
MSG_WARN_FULL_DISK_ACCESS_NOT_GRANTED_TERMINAL="Full Disk Access not granted to Terminal."
MSG_WARN_GB_RAM_DETECTED_WORKS_BUT_LIMITS="%s GB RAM detected. You'll get the compact assistant (gemma4:e2b) – reliable, accurate, sub-second on short questions, with tool calls and an honest 'I don't know' when it doesn't. For richer answers on longer questions, 24 GB or more unlocks the standard assistant (qwen3.5:9b). You can change Macs later by reinstalling."
MSG_WARN_GDPR_IMPORT_HAD_ERRORS_YOU_CAN="GDPR import had errors. You can re-run with:"
MSG_WARN_GDPR_IMPORT_REQUIRED_FOR_PRODUCTISED_INSTALL="GDPR import is part of the productised install. Without it, your social graph (LinkedIn, Facebook, Instagram, WhatsApp, Twitter, Google Calendar) cannot be imported."
MSG_WARN_GDPR_IMPORT_WILL_BE_UNAVAILABLE_THIS_INSTANCE="GDPR import will be unavailable on this instance until the import pipeline is reinstalled."
MSG_WARN_GIT_SAID="Git said:"
MSG_WARN_HEALTH_CHECK_FAILED_OSTLER_KNOWLEDGE_VERSION="  Health check failed: ostler-knowledge --version did not produce output."
MSG_WARN_HEALTH_CHECK_FAILED_PWG_CONVO_HELP="  Health check failed: pwg-convo --help did not return cleanly."
MSG_WARN_HUB_POWER_LAUNCHAGENT_INSTALL_FAILED_SEE="Hub power LaunchAgent install failed. See output above."
MSG_WARN_HUB_POWER_SCRIPTS_MISSING_FROM_APP_BUNDLE="Hub power scripts not found at the expected bundle path."
MSG_WARN_HUB_POWER_SCRIPTS_MISSING_FROM_APP_BUNDLE_2="  The installer .app appears to be missing vendor/hub_power/"
MSG_WARN_HUB_POWER_SCRIPTS_MISSING_FROM_APP_BUNDLE_3="  in Contents/Resources/hub-power/. Battery-aware throttling will not be installed; the rest of the install will continue."
MSG_WARN_IMAGE_PULL_FAILED_NETWORK_DISK_SPACE="  - Image pull failed (network, disk space, or registry timeout)"
MSG_WARN_IMAP_HOST_EMPTY_TRY_AGAIN="IMAP host is empty – try again."
MSG_WARN_IMESSAGE_AUTOMATION_PERMISSION_NOT_GRANTED_1743="iMessage Automation permission: not granted (-1743)."
MSG_WARN_IMESSAGE_AUTOMATION_PERMISSION_PROBE_INCONCLUSIVE="iMessage Automation permission: probe inconclusive."
MSG_WARN_IMESSAGE_NEEDS_LEAST_ONE_ALLOWED_CONTACT="iMessage needs at least one allowed contact. Try again or"
MSG_WARN_IMPORT_PIPELINE_NOT_AVAILABLE_PRIVATE_REPO="Import pipeline not available (private repo - beta testers only)."
MSG_WARN_IMPORT_PIPELINE_NOT_BUNDLED_HARD_FAIL_BYPASSED="Import pipeline not bundled with installer. Hard-fail bypassed."
MSG_WARN_IMPORT_PIPELINE_NOT_BUNDLED_WITH_INSTALLER="Import pipeline not bundled with installer. This is the productised install path; the contact_syncer Python package should ship inside the .app bundle."
MSG_WARN_INBOX_MEANS_ASSISTANT_WILL_READ_EVERY="INBOX means the assistant will read every email you receive."
MSG_WARN_INSUFFICIENT_DISK_WIKI_OUTPUT_VOLUME="  - Insufficient disk for the wiki output volume"
MSG_WARN_INTEL_MAC_DETECTED_PERFORMANCE_WILL_LIMITED="Intel Mac detected – performance will be limited. Apple Silicon recommended."
MSG_WARN_IS_CLOUD_PROVIDER_HOST="%s is a cloud-provider host."
MSG_WARN_JWT_SECRET_BANLIST_REGENERATING_KEEP_CM019="JWT_SECRET in %s is on the banlist; regenerating to keep CM019 services importable"
MSG_WARN_JWT_SECRET_TOO_SHORT_CHARS_REGENERATING="JWT_SECRET in %s is too short (%s < %s chars); regenerating"
MSG_WARN_KNOWLEDGE_REPO_CLONED_BUT_PYPROJECT_TOML="Knowledge repo cloned but pyproject.toml missing; venv setup skipped."
MSG_WARN_KNOWLEDGE_SERVICE_INSTALL_FAILED_CLONE="Knowledge service install failed (clone)."
MSG_WARN_LICENCE_SHIPS_UNDER_GOOGLE_S_GEMMA="Licence: %s ships under Google's Gemma Terms of Use, not Apache 2.0."
MSG_WARN_MACBOOK_DEPLOYMENTS_NEED_THIS_BATTERY_SLEEP="MacBook deployments need this for battery / sleep handling."
MSG_WARN_MACOS_CONTACTS_PERMISSION_WAS_DECLINED_NOT="macOS Contacts permission was declined or not yet granted."
MSG_WARN_MACOS_OUTDATED_WE_RECOMMEND_MACOS_13="macOS %s is outdated. We recommend macOS 13 (Ventura) or later."
MSG_WARN_MACOS_WILL_NOT_PROMPT_IT_FROM="macOS will NOT prompt for it from a script – you must grant it manually."
MSG_WARN_MAC_MINI_DEPLOYMENTS_ARE_UNAFFECTED_MACBOOK="Mac Mini deployments are unaffected; MacBook users should retry."
MSG_WARN_MAIL_DATA_STILL_INGESTIBLE_MANUALLY="Mail data is still ingestible manually:"
MSG_WARN_MANUAL_RETRY_CD_DOCKER_COMPOSE_UP="  Manual retry: cd %s && docker compose up -d vane"
MSG_WARN_MANUAL_RETRY_ONCE_CAUSE_RESOLVED="  Manual retry once the cause is resolved:"
MSG_WARN_NEITHER_APPLE_MAIL_NOR_CUSTOM_IMAP="Neither Apple Mail nor Custom IMAP selected – defaulting to Apple Mail."
MSG_WARN_NO_PASSKEY_SET_DATABASES_WILL_NOT="No passkey set; databases will not be encrypted."
MSG_WARN_RECOVERY_PASSPHRASES_DON_T_MATCH_TRY_AGAIN="Recovery passphrases don't match. Try again."
MSG_WARN_RECOVERY_PASSPHRASE_SETUP_FAILED="Recovery passphrase setup failed. Output:"
MSG_WARN_RECOVERY_PASSPHRASE_SKIPPED="Empty input. Recovery passphrase skipped."
MSG_WARN_RECOVERY_PASSPHRASE_TOO_SHORT="Recovery passphrase must be at least 12 characters. Try again."
MSG_WARN_NUMBER_MUST_START_WITH_TRY_AGAIN="Number must start with +. Try again."
MSG_WARN_OLLAMA_NOT_RESPONDING="Ollama not responding"
MSG_WARN_OLLAMA_PULL_FAILED_ATTEMPT_3_RETRYING="ollama pull %s failed (attempt %s/3). Retrying in %ss..."
MSG_WARN_ONLY_GB_FREE_WE_RECOMMEND_LEAST="Only %s GB free. We recommend at least 35 GB (Docker images + AI model + data)."
MSG_WARN_ON_BATTERY_HUB_POWER_LAUNCHAGENT_STEP="On battery, the hub power LaunchAgent (step 3.14) may pause"
MSG_WARN_OR_RE_RUN_INSTALLER_PICK_DIFFERENT="or re-run the installer and pick a different channel choice."
MSG_WARN_OR_RUNNING_AHEAD_PHASE_B_S="or running ahead of Phase B's release pipeline. Re-run the installer once the"
MSG_WARN_OSTLER_ASSISTANT_DOCTOR_REPORTED_ERROR_S="ostler-assistant doctor reported %s error(s)."
MSG_WARN_OSTLER_ASSISTANT_EXTRACTED_BUT_VERSION_CHECK="ostler-assistant extracted but --version check failed."
MSG_WARN_OSTLER_ASSISTANT_LAUNCHAGENT_INSTALL_FAILED_SEE="Ostler assistant LaunchAgent install failed. See output above."
MSG_WARN_OSTLER_ASSISTANT_V_APPLE_SILICON_ONLY="ostler-assistant v%s is Apple Silicon only (detected: %s)."
MSG_WARN_OSTLER_IMPORT_USER_NAME_VERBOSE="  ostler-import %s --user-name \"%s\" --verbose"
MSG_WARN_OSTLER_WIKI_COMPILER_IMAGE_NOT_YET="  - ostler-wiki-compiler image not yet pullable (registry not wired)"
MSG_WARN_OXIGRAPH_NOT_RESPONDING="Oxigraph not responding"
MSG_WARN_OXIGRAPH_NOT_YET_HEALTHY_THIS_PHASE="  - Oxigraph not yet healthy at this phase (check logs above)"
MSG_WARN_PASSWORDS_DID_NOT_MATCH_WERE_EMPTY="Passwords did not match (or were empty). Try again."
MSG_WARN_PHASE_3_TAKES_10_15_MINUTES="Phase 3 takes 10-15 minutes of Docker + Ollama downloads."
MSG_WARN_PIP_INSTALL_FAILED_CM048_PIPELINE_WILL="  pip install failed; CM048 conversation pipeline will not be available."
MSG_WARN_PIP_INSTALL_FAILED_OSTLER_KNOWLEDGE_WILL="  pip install failed; ostler-knowledge will not be available."
MSG_WARN_PIP_SAID="pip said:"
MSG_WARN_PLUG_INTO_AC_POWER_FULL_INSTALL="Plug into AC power for the full install."
MSG_WARN_PORT_1_ALREADY_USE_PID="Port %s is already in use by %s (PID %s)"
MSG_WARN_PORT_3000_ALREADY_USE_ANOTHER_SERVICE="  - Port 3000 already in use by another service"
MSG_WARN_POWER_SOURCE="Power source: %s"
MSG_WARN_PWG_EMAIL_INGEST_MBOX_TMP_MANUAL="  pwg-email-ingest mbox /tmp/manual.mbox.txt"
MSG_WARN_PYSQLCIPHER3_INSTALL_FAILED="pysqlcipher3 install failed."
MSG_WARN_PYSQLCIPHER3_INSTALL_FAILED_DATABASES_WILL_NOT="pysqlcipher3 install failed. Databases will not be encrypted."
MSG_WARN_PYTHON3_M_OSTLER_FDA_APPLE_MAIL="  python3 -m ostler_fda.apple_mail_mbox --emit-mbox /tmp/manual.mbox.txt"
MSG_WARN_PYTHON_3_NOT_FOUND_INSTALLING_PYTHON="Python 3 not found. Installing Python 3.12..."
MSG_WARN_PYTHON_TOO_OLD_NEED_3_10="Python %s is too old (need 3.10+). Installing Python 3.12..."
MSG_WARN_QDRANT_NOT_RESPONDING="Qdrant not responding"
MSG_WARN_READ_HTTPS_AI_GOOGLE_DEV_GEMMA="         Read https://ai.google.dev/gemma/terms before commercial use."
MSG_WARN_READ_PUBLIC_VERSION_HTTPS_OSTLER_AI="Read the public version at https://ostler.ai/licenses.html"
MSG_WARN_REDIS_NOT_RESPONDING="Redis not responding"
MSG_WARN_RELEASE_LANDS_STAGE_BINARY_MANUALLY="release lands, or stage the binary manually:"
MSG_WARN_RE_RUNNING_TYPE_SELF_HOSTED_HOST="Re-running – type a self-hosted host, or press Ctrl-C and re-launch picking Apple Mail."
MSG_WARN_RE_RUN_INSTALLER_WITH_IMESSAGE_UNTICKED="re-run the installer with iMessage unticked to skip it."
MSG_WARN_RUNNING_WITH_ALLOW_PLAINTEXT_ENCRYPTION_DISABLED="RUNNING WITH --allow-plaintext: encryption disabled. NOT FOR PRODUCTION."
MSG_WARN_RUN_DOCTOR_AFTER_FIRST_LAUNCH="  Run \`%s doctor\` after first launch"
MSG_WARN_RUN_TAILSCALE_IP_4_ONCE_SIGNED="Run 'tailscale ip --4' once signed in, then add the address to the iOS app."
MSG_WARN_SAFARI_EXTENSION_COPY_FAILED_YOU_CAN="Safari extension copy failed; you can install it manually later"
MSG_WARN_SECURITY_MODULE_NOT_FOUND_PASSKEY_SETUP="Security module not found. Passkey setup will be skipped."
MSG_WARN_SECURITY_MODULE_LOOKED_FOR_PATH="  Looked for: %s/ostler_security/pyproject.toml"
MSG_WARN_SECURITY_MODULE_MISSING_FROM_APP_BUNDLE="  This usually means the installer .app was built without"
MSG_WARN_SECURITY_MODULE_MISSING_FROM_APP_BUNDLE_2="  the vendored ostler_security package bundled into"
MSG_WARN_SECURITY_MODULE_MISSING_FROM_APP_BUNDLE_3="  Contents/Resources/. Re-download the installer or"
MSG_WARN_SECURITY_MODULE_MISSING_FROM_APP_BUNDLE_4="  re-run with --allow-plaintext for a dev/CI install."
MSG_WARN_SECURITY_SETUP_FAILED_CONTINUING_WITHOUT_DATABASE="Security setup failed. Continuing without database encryption."
MSG_WARN_SECURITY_SETUP_FAILED_OUTPUT="Security setup failed. Output:"
MSG_WARN_SEE_STDERR_FRAGMENT="  See %s for the stderr fragment."
MSG_WARN_SKIPPING_BINARY_INSTALL_WIZARD_WRITTEN_CONFIG="Skipping binary install. The wizard-written config.toml stays in place."
MSG_WARN_SKIPPING_DOCTOR_LAUNCHAGENT_INSTALL="Skipping Doctor LaunchAgent install."
MSG_WARN_SKIPPING_EMAIL_INGEST_LAUNCHAGENT_INSTALL="Skipping email-ingest LaunchAgent install."
MSG_WARN_SKIPPING_LAUNCHAGENT_INSTALL_MAC_MINI_DEPLOYMENTS="Skipping LaunchAgent install. Mac Mini deployments are unaffected."
MSG_WARN_SKIPPING_LAUNCHAGENT_INSTALL_TRY_VERSION="Skipping LaunchAgent install. Try: %s --version"
MSG_WARN_SKIPPING_WIKI_RECOMPILE_LAUNCHAGENT_INSTALL="Skipping wiki-recompile LaunchAgent install."
MSG_WARN_SOME_FEATURES_MAY_NOT_WORK_CORRECTLY="Some features may not work correctly on older versions."
MSG_WARN_SOME_PORTS_ARE_USE_DOCKER_CONTAINERS="Some ports are in use. Docker containers may fail to start."
MSG_WARN_STOP_CONFLICTING_SERVICES_CHANGE_PORTS_DOCKER="Stop the conflicting services or change the ports in docker-compose.yml"
MSG_WARN_TAILSCALE_DIDN_T_SIGN_WITHIN_60="Tailscale didn't sign in within 60 seconds. You can come back to this later."
MSG_WARN_TAILSCALE_INSTALL_FAILED_YOU_CAN_INSTALL="Tailscale install failed – you can install it later from tailscale.com"
MSG_WARN_THE_DEPLOYED_SERVICES_REFUSE_START_WITHOUT="the deployed services refuse to start without them."
MSG_WARN_THIS_RESOLVED_SEE_NEXT_STEPS_BANNER="  this is resolved. See next-steps banner for remediation."
MSG_WARN_TO_INSPECT_CRON_DELIVERY_IMESSAGE_TCC="  to inspect. cron-delivery / imessage-tcc are common"
MSG_WARN_TRY_DOCKER_COMPOSE_F_DOCKER_COMPOSE="  Try: docker compose -f %s/docker-compose.yml up -d wiki-site"
MSG_WARN_TRY_DOCKER_LOGS_OSTLER_VANE="  Try: docker logs ostler-vane"
MSG_WARN_UNRECOGNISED_CHOICE_DEFAULTING_IMESSAGE_EMAIL="Unrecognised choice '%s'; defaulting to iMessage + email."
MSG_WARN_UNRECOGNISED_CHOICE_USING_RECOMMENDED="Unrecognised choice. Using Recommended."
MSG_WARN_UPDATE_FAILED_CONTINUING_WITH_EXISTING_CHECKOUT="  Update failed; continuing with existing checkout."
MSG_WARN_USE_APPLE_MAIL_RECOMMENDED_ABOVE_THAT="Use Apple Mail (recommended above) for that account – Ostler never stores cloud passwords."
MSG_WARN_USING_INBOX_ASSISTANT_WILL_READ_EVERY="Using INBOX. The assistant will read every incoming email."
MSG_WARN_VANE_CONTAINER_STARTED_BUT_HTTP_LOCALHOST="Vane container started but http://localhost:3000 did not respond within 60s."
MSG_WARN_VANE_LOCAL_WEB_SEARCH_FAILED_START="Vane (local web search) failed to start. Common causes:"
MSG_WARN_WEB_SEARCH_OPTIONAL_REST_OSTLER_WORKS="  Web search is optional; the rest of Ostler works without it."
MSG_WARN_WE_STRONGLY_RECOMMEND_DEDICATED_LABEL_FOLDER="We strongly recommend a dedicated label/folder instead."
MSG_WARN_WHATSAPP_NEEDS_PHONE_NUMBER_BRIEF_DELIVERY="WhatsApp needs a phone number for brief delivery. Try again,"
MSG_WARN_WIKI_COMPILED_BUT_WIKI_SITE_CONTAINER="Wiki compiled but wiki-site container failed to start."
MSG_WARN_WIKI_FIRST_COMPILE_FAILED_COMMON_CAUSES="Wiki first-compile failed. Common causes:"
MSG_WARN_WIKI_RECOMPILE_LAUNCHAGENT_INSTALL_FAILED_SEE="Wiki-recompile LaunchAgent install failed. See output above."
MSG_WARN_WIKI_WILL_NOT_AUTO_UPDATE_MANUAL="Wiki will not auto-update; manual rebuild stays available:"
MSG_WARN_WIZARD_CONFIG_STAYS_PLACE_BINARY_STAYS="Wizard config stays in place; binary stays staged. Manual retry:"
MSG_WARN_YOUR_ASSISTANT_NEEDS_NAME_PICK_FROM="Your assistant needs a name. Pick from the suggestions above or type your own."
MSG_WARN_YOU_CAN_RE_GRANT_IT_SYSTEM="You can re-grant it in System Settings > Privacy & Security > Contacts."
MSG_WARN_YOU_CAN_RUN_SECURITY_SETUP_LATER="You can run the security setup later: python3 -m ostler_security.setup_wizard"
MSG_WARN_YOU_MAY_NEED_INSTALL_MANUALLY_INSTALL="You may need to install manually: %s install pysqlcipher3"

# ── Error messages (security / integrity, hard-fail context) ──

MSG_ERR_ACTUAL="  actual:   %s"
MSG_ERR_CM042_BUNDLE_NOT_FOUND_POST_EXTRACT="Ostler RemoteCapture bundle was not present at %s after extract. The release tarball may be malformed."
MSG_ERR_CM042_CODESIGN_OUTPUT="  codesign --verify reported:"
MSG_ERR_CM042_REFUSING_STAGE_BUNDLE="  Refusing to stage a bundle that does not match the published checksum."
MSG_ERR_CM042_SHA_256_MISMATCH="Ostler RemoteCapture tarball SHA-256 mismatch."
MSG_ERR_CM042_SPCTL_OUTPUT="  spctl --assess reported:"
MSG_ERR_CM042_VERIFY_FAILED="Ostler RemoteCapture signature / notarisation verification failed."
MSG_ERR_CODESIGN_DV_REPORTED="  codesign -dv reported:"
MSG_ERR_EXPECTED="  expected: %s"
MSG_ERR_FILE_BRIEF_REPORTED="  file --brief reported: %s"
MSG_ERR_OSTLER_ASSISTANT_BINARY_NOT_MACH_O="ostler-assistant binary at %s is not a Mach-O executable."
MSG_ERR_OSTLER_ASSISTANT_TARBALL_SHA_256_MISMATCH="ostler-assistant tarball SHA-256 mismatch."
MSG_ERR_REFUSING_STAGE_BINARY_THAT_DOES_NOT="  Refusing to stage a binary that does not match the published checksum."
MSG_ERR_REFUSING_STRIP_QUARANTINE_LOAD_LAUNCHAGENT="Refusing to strip quarantine or load the LaunchAgent."
MSG_ERR_RE_RUN_INSTALLER_ONCE_UPSTREAM_TARBALL="Re-run the installer once the upstream tarball is fixed."
MSG_ERR_URL="  url:      %s"

# ── Fail messages (terminal -- the installer exits after) ──

MSG_FAIL_AT_LEAST_16_GB_RAM_REQUIRED="At least 16 GB RAM required. You have %s GB. 24 GB recommended."
MSG_FAIL_CM042_SIGNATURE_FAILED="Ostler RemoteCapture install aborted: signature or notarisation check failed. The bundle was left in /Applications for support. Email support@ostler.ai and re-run the installer."
MSG_FAIL_COULD_NOT_PULL_AFTER_3_ATTEMPTS="Could not pull %s after 3 attempts. Check your network and re-run the installer."
MSG_FAIL_COULD_NOT_PULL_NOMIC_EMBED_TEXT="Could not pull nomic-embed-text after 3 attempts. Check your network and re-run the installer."
MSG_FAIL_DOCKER_NOT_AVAILABLE_RE_RUN_INSTALLER="Docker not available. Re-run the installer to install Colima."
MSG_FAIL_FDA_MODULE_MISSING_RE_RUN="FDA extraction module is missing from the installer bundle. Re-download the .app from ostler.ai/install, or re-run with --allow-plaintext for dev/CI."
MSG_FAIL_IMPORT_PIPELINE_INSTALL_FAILED_RE_RUN_INSTALLER="Import pipeline install failed. The CM041 contact_syncer bundle is required for the productised install. Re-run with --allow-plaintext for dev/CI, or re-download the installer and try again."
MSG_FAIL_NEED_SUDO_ACCESS_DISABLE_SLEEP_INSTALL="Need sudo access to disable sleep + install Homebrew. Re-run when ready."
MSG_FAIL_NEITHER_COLIMA_NOR_DOCKER_DESKTOP_COULD="Neither Colima nor Docker Desktop could start. Install Docker Desktop and re-run."
MSG_FAIL_NOT_ENOUGH_DISK_SPACE_GB_FREE="Not enough disk space (%s GB). Free up space and try again."
MSG_FAIL_NO_PASSKEY_SET_NO_EXISTING_SECURITY="No passkey set and no existing security configuration. Re-run with --allow-plaintext for dev/CI, or re-run the installer and acknowledge the Touch ID briefing."
MSG_FAIL_CM048_PIPELINE_REQUIRED_RE_RUN="CM048 conversation pipeline is required. Re-run with --allow-plaintext for dev/CI, or fix the missing bundle above and retry."
MSG_FAIL_OSTLER_SECURITY_INSTALL_FAILED_RE_RUN="ostler_security install failed. Re-run with --allow-plaintext for dev/CI, or fix the pip error above and retry."
MSG_FAIL_PASSKEY_SETUP_FAILED_RE_RUN_WITH="Passkey setup failed. Re-run with --allow-plaintext for dev/CI, or fix the error above and retry."
MSG_FAIL_PYSQLCIPHER3_REQUIRED_ENCRYPTED_DATABASES_RE_RUN="pysqlcipher3 is required for encrypted databases. Re-run with --allow-plaintext for dev/CI, or fix the pip error above and retry."
MSG_FAIL_THIS_INSTALLER_MACOS_ONLY_LINUX_SUPPORT="This installer is for macOS only. Linux support coming soon."
MSG_FAIL_XCODE_COMMAND_LINE_TOOLS_INSTALL_DID="Xcode Command Line Tools install did not complete in 10 minutes. Run 'xcode-select --install' manually, accept the dialog, then re-run this installer."

# ── Prompts (gui_read titles + help text) ──
#
# Customer-facing questions the user reads during setup. Each prompt
# id (e.g. "assistant_name") gets a MSG_PROMPT_<UPPER>_TITLE entry,
# and -- where the prompt carries non-empty help / sub-line copy --
# a matching MSG_PROMPT_<UPPER>_HELP entry. Format-string entries
# use printf %s placeholders for runtime values (e.g. detected
# country code, detected timezone).

MSG_PROMPT_REUSE_SETTINGS_TITLE="Continue with these settings?"

MSG_PROMPT_PERMS_OK_TITLE="Ready to continue?"
MSG_PROMPT_PERMS_OK_HELP="macOS will prompt for Contacts and Files & Folders access. Optional Full Disk Access can be granted later."

MSG_PROMPT_USER_NAME_DETECTED_TITLE="Full name (as it appears in your contacts)"
MSG_PROMPT_USER_NAME_FALLBACK_TITLE="Full name (e.g. Tom Harrison)"

MSG_PROMPT_USER_ID_TITLE="What should your assistant call you?"

MSG_PROMPT_COUNTRY_CODE_CONFIRM_TITLE="Use +%s?"
MSG_PROMPT_COUNTRY_CODE_ENTER_TITLE="Enter country code (e.g. 44 for UK, 1 for US)"
MSG_PROMPT_COUNTRY_CODE_DEFAULT_TITLE="Default country code"
MSG_PROMPT_COUNTRY_CODE_DEFAULT_HELP="Used to normalise phone numbers during contact import."

MSG_PROMPT_TZ_CONFIRM_TITLE="Use this timezone?"
MSG_PROMPT_TZ_CONFIRM_HELP="Detected timezone: %s"
MSG_PROMPT_USER_TZ_TITLE="Enter timezone (e.g. Europe/London, Asia/Hong_Kong)"

MSG_PROMPT_ASSISTANT_NAME_TITLE="What would you like to call your assistant?"
MSG_PROMPT_ASSISTANT_NAME_HELP_FULL="The name in the field is a random suggestion – type over it with anything you like. Many people pick something simple. Marvin, Friday, Watson, HAL, JARVIS, and Mycroft are all popular choices." # assistant-name-exempt: F6.1 suggestion-pool exemplar
MSG_PROMPT_ASSISTANT_NAME_HELP_SHORT="Type any name you like – the suggestion is just a starting point."

MSG_PROMPT_CHANNEL_CHOICE_TITLE="How will your assistant reach you?"
MSG_PROMPT_CHANNEL_CHOICE_HELP="Pick the messaging channels you would like your assistant to use. You can change this later in Doctor."

MSG_PROMPT_WHATSAPP_CONSENT_TITLE="Enable WhatsApp connector and accept the risk above?"
MSG_PROMPT_WHATSAPP_CONSENT_HELP="WhatsApp Web access is a third-party integration – you accept the consent above by enabling it."

MSG_PROMPT_WHATSAPP_RECIPIENT_TITLE="Your WhatsApp phone number"
MSG_PROMPT_WHATSAPP_RECIPIENT_HELP="International format, like +44 7700 900000. Leading +, country code, digits only."

MSG_PROMPT_IMESSAGE_ALLOWED_TITLE="Allowed contacts"
MSG_PROMPT_IMESSAGE_ALLOWED_HELP="Allowlist of phone numbers and Apple ID emails (comma-separated). %s only replies to listed contacts; messages from anyone else are ignored. At least one entry required. For example: +447700900000, you@example.com"

MSG_PROMPT_EMAIL_APPLE_MAIL_TITLE="Read mail via Apple Mail?"
MSG_PROMPT_EMAIL_APPLE_MAIL_HELP="Reads any account you have added to Apple Mail (iCloud, Gmail, Outlook, etc.) using Full Disk Access. No passwords stored. Recommended for almost everyone."

MSG_PROMPT_EMAIL_CUSTOM_IMAP_TITLE="Also configure a custom IMAP+SMTP server?"
MSG_PROMPT_EMAIL_CUSTOM_IMAP_HELP="For self-hosted mailboxes only. Skip this if your accounts are with Gmail, iCloud, or Outlook – those work better via Apple Mail above."

MSG_PROMPT_IMAP_HOST_TITLE="IMAP host"
MSG_PROMPT_IMAP_HOST_HELP="Self-hosted or custom IMAP server only. Use Apple Mail (above) for Gmail / iCloud / Outlook."
MSG_PROMPT_IMAP_PORT_TITLE="IMAP port"

MSG_PROMPT_SMTP_HOST_TITLE="SMTP host"
MSG_PROMPT_SMTP_PORT_TITLE="SMTP port"

MSG_PROMPT_EMAIL_USERNAME_TITLE="Email address (also used as IMAP/SMTP username)"

MSG_PROMPT_EMAIL_PASSWORD_TITLE="Password (hidden)"
MSG_PROMPT_EMAIL_PASSWORD_HELP="Password for your self-hosted IMAP/SMTP server. Stored locally under ~/.ostler/ – never sent to Creative Machines."
MSG_PROMPT_EMAIL_PASSWORD_CONFIRM_TITLE="Confirm Password"

MSG_PROMPT_EMAIL_IMAP_FOLDER_TITLE="Which folder should the assistant watch?"
MSG_PROMPT_EMAIL_IMAP_FOLDER_HELP="Recommended: a dedicated label or folder (e.g. Ostler). We will only read messages there, leaving your main inbox untouched."

MSG_PROMPT_EMAIL_INBOX_CONFIRM_TITLE="Type INBOX again to confirm, or press Continue to use 'Ostler'"
MSG_PROMPT_EMAIL_INBOX_CONFIRM_HELP="INBOX means the assistant will read every email you receive. We strongly recommend a dedicated label/folder instead."

MSG_PROMPT_EXPORTS_ACK_TITLE="Request your data exports now"
MSG_PROMPT_EXPORTS_ACK_HELP="You can do this on your phone while the installer runs. Exports usually take 1 to 3 days to arrive by email. When they do, drop them in your Downloads folder and Ostler will find them automatically."

MSG_PROMPT_FILEVAULT_SKIP_TITLE="Continue without FileVault?"
MSG_PROMPT_FILEVAULT_SKIP_HELP="FileVault is strongly recommended. Without it, physical access to your Mac means access to your data."

MSG_PROMPT_PASSKEY_ACK_TITLE="Ready to set up Touch ID encryption"
MSG_PROMPT_PASSKEY_ACK_HELP="Your knowledge graph is encrypted with a key wrapped by Touch ID on this Mac. macOS prompts for Touch ID later in the install. A 12-word recovery phrase is also generated and shown once. Press Continue when you're ready."

MSG_PROMPT_RECOVERY_PASSPHRASE_OPT_IN_TITLE="Set a recovery passphrase too? (recommended)"
MSG_PROMPT_RECOVERY_PASSPHRASE_OPT_IN_HELP="Optional second recovery route. If Touch ID ever fails and you've lost the 12-word phrase, a recovery passphrase you remember lets you back in. Skipping is fine if you trust yourself to keep the recovery phrase safe."
MSG_PROMPT_RECOVERY_PASSPHRASE_TITLE="Enter recovery passphrase"
MSG_PROMPT_RECOVERY_PASSPHRASE_HELP="A separate secondary password. Used only as a fallback if Touch ID fails. Cannot be recovered. We recommend storing it in your password manager."
MSG_PROMPT_RECOVERY_PASSPHRASE_CONFIRM_TITLE="Confirm recovery passphrase"
MSG_PROMPT_RECOVERY_PASSPHRASE_CONFIRM_HELP="Re-enter the same recovery passphrase to confirm."

MSG_PROMPT_IMPORT_CONFIRM_TITLE="Import these during install?"
MSG_PROMPT_IMPORT_CONFIRM_HELP="Found GDPR exports will be imported into your knowledge graph during install."

MSG_PROMPT_MANUAL_EXPORTS_PATH_TITLE="Do you have data exports ready?"
MSG_PROMPT_MANUAL_EXPORTS_PATH_HELP="Ostler can import social media and platform archives – your full history with friends, family, places, opinions – right from the start. The more Ostler knows day one, the more useful it is on day one. (You can also add this later. No rush.)  Request your data export from each platform (Twitter / X, Facebook, Instagram, LinkedIn, WhatsApp, etc.), download the ZIP files, and drop them in your Downloads folder. Ostler will look in ~/Downloads by default. Want a different folder? Pick one below. Otherwise, skip and import later."

MSG_PROMPT_TAKEOUT_CONFIRM_TITLE="Import Gmail messages from this Takeout?"
MSG_PROMPT_TAKEOUT_CONFIRM_HELP="Reads Gmail content from the Takeout file directly. Google never sees Ostler."

MSG_PROMPT_FDA_PRESET_TITLE="Which Mac sources should Ostler learn from?"
MSG_PROMPT_FDA_PRESET_HELP="Three presets, or pick each one yourself. Sensitive sources (face recognition) are off by default in every preset – tick deliberately if you want them."
MSG_PROMPT_FDA_PRESET_CHOICE_RECOMMENDED="Recommended (most people start here)"
MSG_PROMPT_FDA_PRESET_CHOICE_EVERYTHING="Everything (every data source Ostler supports – for power users)"
MSG_PROMPT_FDA_PRESET_CHOICE_CUSTOMISE="Customise (pick exactly which sources)"

MSG_PROMPT_FDA_SOURCE_TOGGLE_HELP="Toggle this data source on or off."

MSG_PROMPT_CONSENT_ARTICLE_9_TITLE="Your decision (Y / N)"
MSG_PROMPT_CONSENT_ARTICLE_9_HELP="Article 9 special-category consent (UK GDPR). Required for the lawful basis of processing."

MSG_PROMPT_CONSENT_VOICE_EU_TITLE="Recognise voices on your call recordings?"
MSG_PROMPT_CONSENT_VOICE_EU_HELP="Speaker recognition stays on this Mac. Creative Machines never receives the fingerprints."

MSG_PROMPT_CONSENT_THIRD_PARTY_TITLE="One last thing: how third-party data works"
MSG_PROMPT_CONSENT_THIRD_PARTY_HELP="Ostler will read data from sources you connect (email, contacts, messages, social archives). This data stays on this Mac. Creative Machines, the company that makes Ostler, never receives any of it. We cannot, even if asked. Some of your data was created by other people (the emails they sent you, the messages they wrote). You are the one deciding to use it on your Mac. By continuing, you are saying you are comfortable with that."

MSG_PROMPT_CONSENT_INSTALL_TITLE="Ready to install"
MSG_PROMPT_CONSENT_INSTALL_HELP="By choosing Install Ostler, you confirm you accept the terms at ostler.ai/terms."
MSG_PROMPT_CONSENT_INSTALL_BUTTON_PRIMARY="Install Ostler"
MSG_PROMPT_CONSENT_INSTALL_BUTTON_CANCEL="Cancel"

MSG_PROMPT_TAILSCALE_CONFIRM_TITLE="Install Tailscale now?"
MSG_PROMPT_TAILSCALE_CONFIRM_HELP="Tailscale lets you reach the assistant securely from your phone or other Macs."

MSG_PROMPT_SAVE_KEYCHAIN_TITLE="Save recovery key to Keychain?"
MSG_PROMPT_SAVE_KEYCHAIN_HELP="Stores your encryption recovery key in the macOS Keychain for safekeeping."

