#!/usr/bin/env bash
#
# test_shipped_compose_licence_mount.sh
#
# THE FILENAME OUTLIVED THE MOUNT IT WAS NAMED FOR, and is kept on purpose:
# it is wired by name in .github/workflows/licence-gate.yml and cited by name
# from two sibling tests as the exemplar of the lesson below. A rename would
# buy tidiness and cost five call sites and the citations.
#
# #849 -- THE PRO OBSIDIAN VAULT WRITER COULD NOT RUN ON ANY INSTALL, AND
# THE TEST THAT SHOULD HAVE CAUGHT IT WAS GREEN THE WHOLE TIME.
#
# CM044 fixed this in its OWN docker/docker-compose.yml and wrote a guard for
# it. That guard reads CM044's dev compose. The customer does not run CM044's
# dev compose -- they run the one generated by THIS file. Measured 2026-08-23,
# control on both sides so neither count is a false zero from reading the
# wrong file:
#
#     CM044 docker/docker-compose.yml   .ostler/licence -> 5
#     CM051 install.sh                  .ostler/licence -> 0
#     control: "wiki-compiler" present in both (5 and 15)
#
# Green test, broken customer. Instrument and defect on different surfaces.
#
# 🗿 AND BOARD ROW 971 IS THE SHARPER HALF, WHICH THIS FILE GUARDED PAST FOR
# THREE WEEKS. Every assertion here was true and the feature was still dead,
# because the address all this plumbing delivered -- ~/.ostler/licence/state.json
# -- IS ONE NOTHING HAS EVER WRITTEN. CM044's own module said so in its
# docstring on 2026-07-30 and asked for confirmation before v1.0.13 merged.
# Nobody answered. A mount, an env var, a workflow and a guard, all correct,
# all pointing at a file with no writer.
#
# So the reader moved to the Hub's own store, ~/.ostler/state/subscription_state.json,
# written by subscription_gate from the StoreKit receipt the phone pushes, and
# read by every pipeline through is_active_or_grace(). Andy decided 2026-09-18
# that the Apple receipt is the truth. CM044 #280 is the reader; this is the
# shipping surface.
#
# THE LESSON THIS FILE NOW CARRIES, beyond the one it was written for: a guard
# can pin a delivery mechanism perfectly and never ask whether anything writes
# what is being delivered. Arm 6 is that question, asked of the compose.
#
# British English throughout.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_SH="$REPO_ROOT/install.sh"
FAILED=0

failure() { echo "FAIL: $*" >&2; FAILED=1; }
pass()    { echo "ok: $*"; }

[ -f "$INSTALL_SH" ] || { echo "FAIL: install.sh not found -- CANNOT-RUN, not a pass" >&2; exit 1; }

# ── Control FIRST. ───────────────────────────────────────────────────
# Every assertion below is a grep over install.sh. If the wiki-compiler
# service is not in this file at all, every one of them would report a
# clean, confident zero for a reason that has nothing to do with the
# subject. Establish the denominator before trusting any count.
compiler_hits="$(grep -c 'wiki-compiler' "$INSTALL_SH")"
if [ "$compiler_hits" -lt 1 ]; then
    echo "FAIL: no wiki-compiler service in install.sh -- this test's" >&2
    echo "      subject is absent, so its zeros mean nothing. CANNOT-RUN." >&2
    exit 1
fi
pass "control: wiki-compiler present in install.sh (${compiler_hits} hits)"

# ── 1. The mount that delivers the entitlement exists. ───────────────
# It is the SAME mount that already carried the hydration status file, so
# this fix added nothing: the Hub's subscription state was inside the
# container all along, one directory away from a reader looking elsewhere.
if grep -qE '^\s*-\s*\$\{HOME\}/\.ostler/state:/state\s*$' "$INSTALL_SH"; then
    pass "the shipped compose bind-mounts \${HOME}/.ostler/state"
else
    failure "the shipped wiki-compiler has NO \${HOME}/.ostler/state mount. \
compiler/vault_licence.py will resolve /root/.ostler/state/subscription_state.json, \
a path no install has, and fail-closed to pro_none -- every Pro customer \
silently gets no Obsidian vault (#849, and row 971 underneath it)."
fi

# ── 2. The dead licence mount is GONE. ───────────────────────────────
# Not tidiness. Leaving it keeps a second entitlement address alive in the
# SHIPPED compose for the next person to wire something to, and two stores
# for one fact is the defect row 971 exists to close rather than relocate.
lic_mounts="$(grep -E '^\s*-\s*\$\{HOME\}/\.ostler/licence:' "$INSTALL_SH" || true)"
if [ -z "$lic_mounts" ]; then
    pass "the \${HOME}/.ostler/licence mount is gone with the file nothing wrote"
else
    failure "install.sh still mounts \${HOME}/.ostler/licence. Nothing has ever \
written a file under it; a mount to an address with no writer is how row 971 \
survived three weeks of green guards. Got: ${lic_mounts}"
fi

# ── 3. It is NOT the whole of ~/.ostler. ─────────────────────────────
# The lazy fix is to mount ~/.ostler wholesale, which also hands the
# compiler daemon config and store credentials. Refuse that shape.
if grep -qE '^\s*-\s*\$\{HOME\}/\.ostler:/' "$INSTALL_SH"; then
    failure "install.sh mounts ALL of \${HOME}/.ostler into a container. \
Scope it: the compiler needs state/, not daemon config and store credentials."
else
    pass "no wholesale \${HOME}/.ostler mount (scoped, not blanket)"
fi

# ── 4. The path is EXPLICIT, not HOME-relative. ──────────────────────
# The image declares no USER and no ENV HOME, so "~" is /root only by
# inheritance from the base image. The day anyone adds a USER line, a
# HOME-relative resolution stops matching and the writer goes quiet in
# exactly the #849 way -- with no error, because the reader fail-closes.
if grep -qE '^\s*-\s*OSTLER_SUBSCRIPTION_STATE=/state/subscription_state\.json\s*$' "$INSTALL_SH"; then
    pass "OSTLER_SUBSCRIPTION_STATE is set explicitly to /state/subscription_state.json"
else
    failure "OSTLER_SUBSCRIPTION_STATE is not pinned to \
/state/subscription_state.json. Without it the reader falls back to \
~/.ostler/state/subscription_state.json, which is /root/... only by \
base-image inheritance -- a USER line would silently break it again and \
nothing would say so."
fi

# ── 5. The env var points INSIDE a declared mount target. ────────────
# The two halves can drift independently: someone renames the mount
# target and the env var keeps naming the old one. Then the file is
# mounted, the var is set, and the reader still finds nothing.
#
# HERESTRING, not `printf | grep -q`, wherever a pipeline is involved in
# this file. It sets pipefail, and grep -q exits the instant it matches, so
# the producer dies on SIGPIPE (141) and pipefail promotes that to the
# pipeline's status. Which side wins is decided by process scheduling, so
# the verdict is a coin flip that usually lands green.
# tests/test_pipefail_shortcircuit_inversion.sh ratchets against that
# construct estate-wide and caught the previous version of this very file.
if grep -qE 'OSTLER_SUBSCRIPTION_STATE=/state/' "$INSTALL_SH" \
   && grep -qE '\.ostler/state:/state' "$INSTALL_SH"; then
    pass "the env var's path lands inside the declared mount target"
else
    failure "OSTLER_SUBSCRIPTION_STATE and the mount target disagree. Both \
can be individually present and still not meet."
fi

# ── 6. THE QUESTION THE OLD VERSION NEVER ASKED. ─────────────────────
# The old variable must be absent, not merely superseded. A half-done
# rename that leaves both live is the two-address state this change exists
# to end, and it would look completely healthy: every other arm above
# would still pass.
old_env="$(grep -c 'OSTLER_LICENCE_STATE_FILE' "$INSTALL_SH" || true)"
if [ "$old_env" -eq 0 ]; then
    pass "the superseded OSTLER_LICENCE_STATE_FILE appears nowhere in install.sh"
else
    failure "install.sh still names OSTLER_LICENCE_STATE_FILE (${old_env} \
occurrence(s)). Two entitlement addresses in one shipped artefact is the \
defect, not the leftover."
fi

echo
if [ "$FAILED" -eq 0 ]; then echo "RESULT: PASS"; else echo "RESULT: FAIL"; fi
exit "$FAILED"
