#!/usr/bin/env bash
#
# test_shipped_compose_licence_mount.sh
#
# #849 -- THE PRO OBSIDIAN VAULT WRITER COULD NOT RUN ON ANY INSTALL, AND
# THE TEST THAT SHOULD HAVE CAUGHT IT WAS GREEN THE WHOLE TIME.
#
# CM044 fixed this in its OWN docker/docker-compose.yml and wrote
# test_licence_dir_is_bind_mounted to guard it. That test reads CM044's
# dev compose. The customer does not run CM044's dev compose -- they run
# the one generated by THIS file. Measured 2026-08-23, control on both
# sides so neither count is a false zero from reading the wrong file:
#
#     CM044 docker/docker-compose.yml   .ostler/licence -> 5
#     CM051 install.sh                  .ostler/licence -> 0
#     control: "wiki-compiler" present in both (5 and 15)
#
# Green test, broken customer. Instrument and defect on different
# surfaces. This test exists so the assertion lives on the SHIPPING
# surface; keep CM044's too, they guard different artefacts.
#
# British English throughout.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_SH="$REPO_ROOT/install.sh"
FAILED=0

failure() { echo "FAIL: $*" >&2; FAILED=1; }
pass()    { echo "ok: $*"; }

[ -f "$INSTALL_SH" ] || { echo "FAIL: install.sh not found -- CANNOT-RUN, not a pass" >&2; exit 1; }

# ── Control FIRST. ───────────────────────────────────────────────────
# Every assertion below is a grep over install.sh. If the wiki-compiler
# service is not in this file at all, every one of them would report a
# clean, confident zero for a reason that has nothing to do with #849.
# Establish the denominator before trusting any count.
compiler_hits="$(grep -c 'wiki-compiler' "$INSTALL_SH")"
if [ "$compiler_hits" -lt 1 ]; then
    echo "FAIL: no wiki-compiler service in install.sh -- this test's" >&2
    echo "      subject is absent, so its zeros mean nothing. CANNOT-RUN." >&2
    exit 1
fi
pass "control: wiki-compiler present in install.sh (${compiler_hits} hits)"

# ── 1. The mount exists. ─────────────────────────────────────────────
if grep -qE '^\s*-\s*\$\{HOME\}/\.ostler/licence:/licence:ro\s*$' "$INSTALL_SH"; then
    pass "the shipped compose bind-mounts \${HOME}/.ostler/licence read-only"
else
    failure "the shipped wiki-compiler has NO \${HOME}/.ostler/licence mount. \
compiler/vault_licence.py will resolve /root/.ostler/licence/state.json, a \
path no install has, and fail-closed to pro_none -- every Pro customer \
silently gets no Obsidian vault (#849)."
fi

# ── 2. It is READ-ONLY. ──────────────────────────────────────────────
# Asserted separately from (1) so a future edit that drops :ro fails
# with a message about privilege, not about absence.
# HERESTRING, not `printf | grep -q`. This file sets pipefail, and grep -q
# exits the instant it matches -- the producer then dies on SIGPIPE (141)
# and pipefail promotes that to the pipeline's status. Which side wins is
# decided by process scheduling, so the verdict is a coin flip that
# usually lands green. tests/test_pipefail_shortcircuit_inversion.sh
# ratchets against this construct estate-wide and caught this very line.
lic_mounts="$(grep -E '^\s*-\s*\$\{HOME\}/\.ostler/licence:' "$INSTALL_SH" || true)"
if [ -n "$lic_mounts" ] && ! grep -qv ':ro' <<< "$lic_mounts"; then
    pass "the licence mount is read-only (compiler consumes, never writes)"
else
    failure "a \${HOME}/.ostler/licence mount is not :ro. The wiki compiler \
is a CONSUMER of licence state; a writable mount onto the licence tree is a \
foothold it has no reason to hold. Got: ${lic_mounts:-<none>}"
fi

# ── 3. It is NOT the whole of ~/.ostler. ─────────────────────────────
# The lazy fix is to mount ~/.ostler wholesale, which also hands the
# compiler daemon config and store credentials. Refuse that shape.
if grep -qE '^\s*-\s*\$\{HOME\}/\.ostler:/' "$INSTALL_SH"; then
    failure "install.sh mounts ALL of \${HOME}/.ostler into a container. \
Scope it: the compiler needs licence/ and state/, not daemon config and \
store credentials."
else
    pass "no wholesale \${HOME}/.ostler mount (scoped, not blanket)"
fi

# ── 4. The path is EXPLICIT, not HOME-relative. ──────────────────────
# The image declares no USER and no ENV HOME, so "~" is /root only by
# inheritance from the base image. The day anyone adds a USER line, a
# HOME-relative resolution stops matching and the writer goes quiet in
# exactly the #849 way -- with no error, because the reader fail-closes.
if grep -qE '^\s*-\s*OSTLER_LICENCE_STATE_FILE=/licence/state\.json\s*$' "$INSTALL_SH"; then
    pass "OSTLER_LICENCE_STATE_FILE is set explicitly to /licence/state.json"
else
    failure "OSTLER_LICENCE_STATE_FILE is not pinned to /licence/state.json. \
Without it the reader falls back to ~/.ostler/licence/state.json, which is \
/root/... only by base-image inheritance -- a USER line would silently break \
it again and nothing would say so."
fi

# ── 5. The env var points INSIDE a declared mount target. ────────────
# The two halves can drift independently: someone renames the mount
# target and the env var keeps naming the old one. Then the file is
# mounted, the var is set, and the reader still finds nothing.
if grep -qE 'OSTLER_LICENCE_STATE_FILE=/licence/' "$INSTALL_SH" \
   && grep -qE ':/licence:ro' "$INSTALL_SH"; then
    pass "the env var's path lands inside the declared mount target"
else
    failure "OSTLER_LICENCE_STATE_FILE and the mount target disagree. Both \
can be individually present and still not meet."
fi

echo
if [ "$FAILED" -eq 0 ]; then echo "RESULT: PASS"; else echo "RESULT: FAIL"; fi
exit "$FAILED"
