#!/usr/bin/env bash
#
# test_shipped_compose_usage_journal_mount.sh
#
# #482 -- THE BURSAR SAID "You're not on the meter" ON A BOX THAT HAD DONE
# A FULL INSTALL AND COMPILED A WIKI, AND THIS IS #849 A SECOND TIME.
#
# CM044 fbc115e (2026-08-25) shipped the whole enriching producer --
# compiler/usage_journal.py, its wiring into compiler/llm.py, a vendor-drift
# test, AND the mount that makes the journal visible. It added that mount to
# CM044's OWN docker/docker-compose.yml. The customer does not run CM044's
# dev compose; they run the one generated by THIS file. Measured on CM051
# ddd2dfe9, control on both sides so neither count is a false zero:
#
#     CM044 docker/docker-compose.yml   OSTLER_WORKSPACE -> 4
#     CM051 install.sh                  OSTLER_WORKSPACE -> 0
#     control: OSTLER_WIKI_DIR -> 6 in install.sh
#
# Green tests, broken customer -- the identical shape as its sibling
# test_shipped_compose_licence_mount.sh, which says it outright:
# "A guard on the dev compose says nothing about the artefact."
# That lesson was already written down and it happened again anyway, so
# this file exists to put the assertion on the SHIPPING surface. Keep
# CM044's tests too: they guard a different artefact.
#
# WHAT BREAKS WITHOUT THIS: resolve_journal_path() falls through to its
# last branch and returns /root/.ostler/workspace/state/costs.jsonl -- a
# path inside the container, on no volume, discarded when the compile
# exits. Every compile appends usage records into nothing. No error, no
# warning; it is indistinguishable from a producer nobody ever wired.
#
# British English throughout.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_SH="$REPO_ROOT/install.sh"
FAILED=0

failure() { echo "FAIL: $*" >&2; FAILED=1; }
pass()    { echo "ok: $*"; }

[ -f "$INSTALL_SH" ] || { echo "FAIL: install.sh not found -- CANNOT-RUN, not a pass" >&2; exit 1; }

# ── Control FIRST. ───────────────────────────────────────────────────
# Every assertion below is a grep over install.sh. If the wiki-compiler
# service is absent, all of them report a clean, confident zero for a
# reason that has nothing to do with #482. Denominator before counts.
compiler_hits="$(grep -c 'wiki-compiler' "$INSTALL_SH")"
if [ "$compiler_hits" -lt 1 ]; then
    echo "FAIL: no wiki-compiler service in install.sh -- this test's" >&2
    echo "      subject is absent, so its zeros mean nothing. CANNOT-RUN." >&2
    exit 1
fi
pass "control: wiki-compiler present in install.sh (${compiler_hits} hits)"

# ── 1. The mount exists. ─────────────────────────────────────────────
# THE SOURCE MUST BE THE DAEMON'S WORKSPACE. #482 RESIDUAL, corrected here:
# the earlier version pinned the mount SOURCE as ${HOME}/.ostler/workspace and
# install.sh shipped that same path -- but the daemon does NOT read there. Its
# CostTracker reads <workspace>/state/costs.jsonl, and on a customer box
# <workspace> is ${HOME}/.ostler/assistant-config/workspace: the assistant
# LaunchAgent (com.creativemachines.ostler.assistant.plist) sets
# ZEROCLAW_WORKSPACE=${OSTLER_DIR}/assistant-config, config.toml lives there,
# and resolve_config_dir_for_workspace appends "workspace". A source of
# ~/.ostler/workspace therefore writes every enriching record to a directory
# nothing reads back -- the SAME silent-path shape #482 is about, one level in.
# The property is source==reader, never the spelling of one path; 1b refuses
# the old source so PRESENT-of-the-right-one cannot pass a both-lines half-edit.
# The heredoc is QUOTED, so this text is written verbatim into the customer's
# compose and resolved by docker compose at `up` time.
if grep -qE '^\s*-\s*\$\{OSTLER_WORKSPACE:-\$\{HOME\}/\.ostler/assistant-config/workspace\}/state:/workspace/state\s*$' "$INSTALL_SH"; then
    pass "the shipped compose bind-mounts the DAEMON'S workspace (assistant-config/workspace) state dir at /workspace/state"
else
    failure "the shipped wiki-compiler has NO /workspace/state mount whose SOURCE \
is the daemon's workspace (\$\{HOME\}/.ostler/assistant-config/workspace). Without \
it the enriching journal lands where the daemon's CostTracker never looks (it \
reads assistant-config/workspace/state), and the Bursar reads an empty month \
forever (#482 residual)."
fi

# ── 1b. NEGATIVE: the old WRONG mount source must be gone. ───────────
# Asserting the right path is PRESENT is not enough: a half-edit shipping both
# lines would still pass 1. The bug was a source of ${HOME}/.ostler/workspace,
# a real host directory the daemon's CostTracker never reads. Refuse it by name.
if grep -qE '^\s*-\s*\$\{OSTLER_WORKSPACE:-\$\{HOME\}/\.ostler/workspace\}/state:/workspace/state\s*$' "$INSTALL_SH"; then
    failure "the shipped compose still mounts ~/.ostler/workspace/state as the \
usage-journal source. The daemon reads assistant-config/workspace/state; this \
source sends every enriching record to a directory the Bursar never opens (#482)."
else
    pass "the old wrong mount source (~/.ostler/workspace) is absent"
fi

# ── 2. It is state/ ALONE, not the whole workspace. ──────────────────
# The workspace tree also holds daemon config and store credentials. The
# lazy fix mounts all of it; refuse that shape the way the licence mount
# already does.
if grep -qE '^\s*-\s*\$\{OSTLER_WORKSPACE(:-[^}]*\})?\}?:/workspace\s*$' "$INSTALL_SH" \
   || grep -qE '^\s*-\s*\$\{HOME\}/\.ostler/(assistant-config/)?workspace:/' "$INSTALL_SH"; then
    failure "install.sh mounts the WHOLE workspace into the wiki compiler. \
Scope it to state/: that tree also holds daemon config and store credentials, \
which the compiler has no reason to read."
else
    pass "the workspace mount is scoped to state/, not the whole tree"
fi

# ── 3. The env var is EXPLICIT, not HOME-relative. ───────────────────
# The image declares no USER and no ENV HOME, so "~" is /root only by
# inheritance from the base image. A HOME-relative resolution would stop
# matching the day anyone adds a USER line, and the journal would go quiet
# again in exactly the #482 way -- silently, because a producer writing to
# the wrong path cannot tell that it is wrong.
if grep -qE '^\s*-\s*OSTLER_WORKSPACE=/workspace\s*$' "$INSTALL_SH"; then
    pass "OSTLER_WORKSPACE is pinned explicitly to /workspace"
else
    failure "OSTLER_WORKSPACE is not pinned to /workspace in the shipped \
compose. Without it resolve_journal_path() takes its LAST branch, not branch 2, \
and lands on ~/.ostler/workspace inside the container."
fi

# ── 4. The env var and the mount target must MEET. ───────────────────
# Both halves can drift independently: rename the mount target and the env
# var keeps naming the old one. Then the directory is mounted, the var is
# set, and the producer still writes somewhere nothing reads. This is the
# assertion that catches a half-edit.
#
# /workspace + branch 2's own rule: because the value's basename is
# literally "workspace", resolve_journal_path() uses it as-is instead of
# appending "workspace" again, so the journal lands at
# /workspace/state/costs.jsonl -- inside the mount target below.
if grep -qE 'OSTLER_WORKSPACE=/workspace' "$INSTALL_SH" \
   && grep -qE ':/workspace/state' "$INSTALL_SH"; then
    pass "the env var's workspace root contains the declared mount target"
else
    failure "OSTLER_WORKSPACE and the /workspace/state mount target disagree. \
Both can be individually present and still never meet -- which reads exactly \
like a working producer."
fi

# ── 5. The reader and the writer must name the SAME leaf. ────────────
# The daemon's CostTracker::resolve_storage_path is <workspace>/state/costs.jsonl.
# If the mount target ever moves off .../state, the producer writes a real
# file on the host that the Bursar never opens -- worse than empty, because
# the data exists and looks fine on disk.
if grep -qE ':/workspace/state\s*$' "$INSTALL_SH"; then
    pass "the mount target ends at /workspace/state, matching the reader's <workspace>/state"
else
    failure "the mount target does not end at /workspace/state. The daemon \
reads <workspace>/state/costs.jsonl; a target anywhere else means the journal \
is written to the host and never read back."
fi

echo
if [ "$FAILED" -eq 0 ]; then echo "RESULT: PASS"; else echo "RESULT: FAIL"; fi
exit "$FAILED"
