#!/usr/bin/env bash
# scripts/candidate_vendor.sh <tree> --to <ref> [--dry-run]
# ============================================================================
# STEP (a): graft a merged source change into vendor/<tree>.
#
# scripts/sync_vendor.sh does the graft (materialise source@sha, re-apply the
# divergence patch, copy, regenerate the patch, bump pinned_sha). This wrapper
# is the part an agent did by hand around it: decide the sha, prove the graft is
# a real forward move, and refuse the trees that must not be machine-grafted.
#
# The target sha comes from the GitHub API for the source repo named in
# scripts/candidate_sources.tsv, never from a typed value. Refuses on:
#   - a tree absent from vendor/VENDOR_MANIFEST.toml
#   - a tree with regenerate_forbidden = true (the patch export is a PII hazard
#     and is a human job) or verify = "skip" / pinned_sha = WORKING_TREE
#   - a source repo with no entry in candidate_sources.tsv
#   - a target that is not AHEAD of the pinned sha (behind, diverged, unknown)
#   - a target that changes nothing under the tree's source_path
#   - a tree with no divergence patch, no byte-identical declaration and no
#     unrecorded_divergence record, so the divergence would have no record
#   - a local source checkout that does not contain the target sha
# Idempotent: a tree already pinned at the target is a no-op.
#
# Exit: 0 done / already done, 1 refused, 2 CANNOT-RUN.
# ============================================================================
set -uo pipefail
CAND_ROOT="${CANDIDATE_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
# shellcheck source=scripts/candidate_lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/candidate_lib.sh"

TREE=""; TO=""
while [ $# -gt 0 ]; do
	case "$1" in
		--to) [ $# -ge 2 ] || cand_cannot "--to needs a value"; TO="$2"; shift 2 ;;
		--dry-run) CAND_DRY=1; shift ;;
		-h|--help) sed -n '2,26p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
		-*) cand_cannot "unknown argument: $1" ;;
		*) TREE="$1"; shift ;;
	esac
done
[ -n "$TREE" ] && [ -n "$TO" ] || cand_cannot "usage: candidate_vendor.sh <tree> --to <ref> [--dry-run]"

VM="${CANDIDATE_VENDOR_MANIFEST:-$CAND_ROOT/vendor/VENDOR_MANIFEST.toml}"
SRC_TSV="${CANDIDATE_SOURCES_TSV:-$CAND_ROOT/scripts/candidate_sources.tsv}"
[ -f "$VM" ] || cand_cannot "no vendor manifest at $VM"
[ -f "$SRC_TSV" ] || cand_cannot "no source map at $SRC_TSV"

# one [[tree]] block -> key=value lines (flat schema; comments and blank lines dropped)
block="$(awk -v t="$TREE" '
	/^\[\[tree\]\]/ {inb=0; next_is=1; buf=""; next}
	{ if ($0 ~ /^[[:space:]]*name[[:space:]]*=/) { v=$0; sub(/^[^=]*=[[:space:]]*"/,"",v); sub(/".*/,"",v); if (v==t) inb=1; else inb=0 }
	  if (inb && $0 !~ /^[[:space:]]*#/ && $0 ~ /=/) print }' "$VM")"
[ -n "$block" ] || cand_refuse "tree '$TREE' is not in $VM. Known trees: $(grep -E '^name[[:space:]]*=' "$VM" | sed 's/.*"\(.*\)".*/\1/' | tr '\n' ' ')"
field() { printf '%s\n' "$block" | sed -n "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*\"\{0,1\}\([^\"#]*[^\"# ]\)\"\{0,1\}[[:space:]]*\(#.*\)\{0,1\}\$/\1/p" | head -1; }

pinned="$(field pinned_sha)"; srcrepo="$(field source_repo)"; srcpath="$(field source_path)"
verify="$(field verify)"; patch="$(field divergence_patch)"; unrec="$(field unrecorded_divergence)"
forbid="$(field regenerate_forbidden)"
[ "$forbid" != "true" ] || cand_refuse "$TREE is regenerate_forbidden: its divergence patch cannot be regenerated by a script (PII-export hazard). Graft it by hand per the manifest note."
[ "$verify" != "skip" ] || cand_refuse "$TREE is verify = \"skip\": nothing can prove a graft landed. Human step."
[ "$pinned" != "WORKING_TREE" ] || cand_refuse "$TREE has no git source (pinned_sha = WORKING_TREE), so there is no sha to graft to."
[[ "$pinned" =~ ^[0-9a-f]{40}$ ]] || cand_refuse "$TREE pinned_sha '$pinned' is not a 40-character sha."
[ -n "$patch" ] || [ -n "$unrec" ] || [ "$(field byte_identical)" = "true" ] || \
	cand_refuse "$TREE records no divergence (no divergence_patch, no unrecorded_divergence). Add the record first; a graft with no record is invisible to the gate."
[ -z "$patch" ] || [ -f "$CAND_ROOT/$patch" ] || cand_refuse "$TREE names divergence_patch $patch but the file is missing."

placeholder="$(printf '%s' "$srcrepo" | sed 's#^\$\([A-Za-z0-9_]*\).*#\1#')"
slug="$(awk -F'\t' -v p="$placeholder" '!/^#/ && $1==p {print $2}' "$SRC_TSV" | head -1)"
[ -n "$slug" ] || cand_refuse "source '$srcrepo' (placeholder '$placeholder') has no GitHub slug in $SRC_TSV."

target="$(cand_resolve_commit "$slug" "$TO")" || exit $?
if [ "$target" = "$pinned" ]; then cand_say "[vendor] $TREE already pinned at ${target:0:8} -- nothing to do"; exit 0; fi

cmpjson="$(cand_gh "repos/$slug/compare/$pinned...$target" 2>/dev/null)" || \
	cand_refuse "the API could not compare ${pinned:0:8}...${target:0:8} in $slug."
status="$(printf '%s' "$cmpjson" | jq -r .status 2>/dev/null)"
[ "$status" = "ahead" ] || cand_refuse "$target is '$status' relative to the pin ${pinned:0:8}, not ahead. A graft moves the pin forward along history."
prefix="$srcpath"; [ "$prefix" = "." ] && prefix=""
changed="$(printf '%s' "$cmpjson" | jq -r --arg p "$prefix" '.files[]? | .filename | select($p=="" or startswith($p + "/"))')"
[ -n "$changed" ] || cand_refuse "no file under '$srcpath' changed between ${pinned:0:8} and ${target:0:8}; there is nothing to graft into $TREE."

n="$(printf '%s\n' "$changed" | wc -l | tr -d ' ')"
cand_say "[vendor] $TREE  $slug  ${pinned:0:8} -> ${target:0:8}  ($n file(s) under $srcpath)"
printf '%s\n' "$changed" | sed 's/^/[vendor]   /'

if [ "$CAND_DRY" -eq 1 ]; then
	cand_say "[vendor] would run: scripts/sync_vendor.sh $TREE --to-sha $target"
	cand_say "[vendor] would rewrite: vendor/$TREE, $patch, pinned_sha in vendor/VENDOR_MANIFEST.toml"
	exit 0
fi

envvar="$placeholder"; checkout="${!envvar:-}"
[ -n "$checkout" ] && [ -d "$checkout" ] || cand_cannot "sync_vendor.sh reads the source from a local checkout: set \$$envvar to a clone of $slug."
git -C "$checkout" cat-file -e "$target^{commit}" 2>/dev/null || \
	cand_refuse "the checkout at \$$envvar does not contain $target. Run: git -C \"$checkout\" fetch origin"
SYNC="${CANDIDATE_SYNC_VENDOR:-$CAND_ROOT/scripts/sync_vendor.sh}"
bash "$SYNC" "$TREE" --to-sha "$target" || cand_refuse "sync_vendor.sh failed for $TREE (above). The tree may be partly written; check git status."
exit 0
