#!/usr/bin/env bash
# scripts/new_cut.sh <version> --daemon <sha> --cm051 <sha> --reason "<why>"
# ============================================================================
# START A CUT IN ONE COMMAND, AND LEARN EVERY RED AT ONCE.
#
# WHY THIS EXISTS. Andy, 2026-08-26: "i don't understand why this assembly of
# the cut cant be seamless each time. reuse the previous one and just change
# what is different."
#
# He is right, and the measurement backs him. A cut directory is TWO files, and
# the entire semantic delta between two consecutive cuts is THREE LINES:
#
#     $ diff <(grep -v '^#' cuts/v1.0.45/cut.env) <(grep -v '^#' cuts/v1.0.46/cut.env)
#     < CUT_VERSION=1.0.45          > CUT_VERSION=1.0.46
#     < DAEMON_COMMIT=c4c5b40b408e  > DAEMON_COMMIT=509c8333
#     < CM051=1fc55f50...           > CM051=c32b6736...
#
# Everything else in cut.env is comments -- the REASONING, which is the point
# of the file and is preserved verbatim. MUST_CONTAIN.tsv is generated by
# sync_cut_bom.sh, which already existed. Nothing else is per-cut.
#
# WHAT ACTUALLY COST v1.0.46 FIVE TAG PUSHES. Not the build: `make ship` ran
# clean every time it was reached. It was that the cut's INPUTS are established
# one failure at a time, at tag time, in CI:
#
#     push -> die on the vendored BOM        -> fix -> push
#           -> die on check-pr-age           -> fix -> push
#           -> die on check-orphans (#1080)  -> fix -> push
#           -> die on check-orphans (#1082)  -> fix -> push -> green
#
# Five round trips to learn four things, three of which are one missing
# directory. #1087 created cut-manifests/v1.0.47.yaml and NOT cuts/v1.0.47/ --
# two directories per cut, one of them made by hand, and the other discovered
# by a gate. That seam is the whole defect.
#
# THIS SCRIPT MAKES NO DECISIONS. It copies the previous cut, rewrites exactly
# the three values you name, vendors the BOM, then runs EVERY gate the cut runs
# and prints ALL of them -- green and red together -- so one invocation tells
# you the whole truth instead of a quarter of it.
#
# It deliberately does NOT tag. The tag is the ship; a human decides that.
#
# Exit: 0 every gate green (safe to tag), 1 at least one red, 2 cannot run.
# ============================================================================
set -uo pipefail

die() { echo "ERROR: $*" >&2; exit 2; }

VERSION=""; DAEMON=""; CM051=""; REASON=""
while [ $# -gt 0 ]; do
  case "$1" in
    --daemon) DAEMON="${2:-}"; shift 2 ;;
    --cm051)  CM051="${2:-}";  shift 2 ;;
    --reason) REASON="${2:-}"; shift 2 ;;
    -*) die "unknown flag $1" ;;
    *)  VERSION="$1"; shift ;;
  esac
done
[ -n "$VERSION" ] || die "usage: new_cut.sh <version> --daemon <sha> --cm051 <sha> --reason \"<why>\""
case "$VERSION" in v*) ;; *) die "version must start with v (got '$VERSION')" ;; esac
[ -n "$DAEMON" ] || die "--daemon is required. It is the daemon commit this cut SHIPS, and guessing it is how a cut ends up pinned to a tree nobody built."
[ -n "$CM051" ]  || die "--cm051 is required. It is the CM051 commit whose install.sh blob ships."
[ -n "$REASON" ] || die "--reason is required. cut.env is a REASONING document; a pin with no recorded why cannot be audited later, only obeyed."

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO" || die "cannot cd to repo root"
[ -d cuts ] || die "no cuts/ directory here -- wrong repo?"

NEW="cuts/$VERSION"
[ -e "$NEW" ] && die "$NEW already exists. Refusing to overwrite a cut that has already been started."

# PREVIOUS CUT = highest existing version dir, by version sort, that has a cut.env.
PREV=""
while IFS= read -r d; do
  [ -f "cuts/$d/cut.env" ] && PREV="$d"
done < <(ls cuts 2>/dev/null | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+' | sort -t. -k1,1V -k2,2n -k3,3n)
[ -n "$PREV" ] || die "no previous cut with a cut.env to copy from"
echo "[new-cut] previous cut: $PREV"

mkdir -p "$NEW" || die "cannot create $NEW"
cp "cuts/$PREV/cut.env" "$NEW/cut.env" || die "cannot copy cut.env"

BARE="${VERSION#v}"
# Rewrite EXACTLY the three assignment lines. Anchored to line start so a
# mention inside a comment is never rewritten -- the comments are the record.
/usr/bin/sed -i '' \
  -e "s|^CUT_VERSION=.*|CUT_VERSION=${BARE}|" \
  -e "s|^DAEMON_COMMIT=.*|DAEMON_COMMIT=${DAEMON}|" \
  -e "s|^CM051=.*|CM051=${CM051}|" \
  "$NEW/cut.env" || die "sed failed on $NEW/cut.env"

# Prove the rewrite instead of trusting it. A sed that matched nothing exits 0.
for pair in "CUT_VERSION=${BARE}" "DAEMON_COMMIT=${DAEMON}" "CM051=${CM051}"; do
  grep -qx -- "$pair" "$NEW/cut.env" || die "rewrite did not take: '$pair' is not in $NEW/cut.env"
done
echo "[new-cut] cut.env written: CUT_VERSION=${BARE} DAEMON_COMMIT=${DAEMON} CM051=${CM051:0:12}"

{
  echo ""
  echo "# ---------------------------------------------------------------------------"
  echo "# ${VERSION}, opened by scripts/new_cut.sh from ${PREV}."
  echo "#"
  echo "# WHY THESE PINS:"
  printf '%s\n' "$REASON" | /usr/bin/fold -s -w 74 | /usr/bin/sed 's/^/#   /'
  echo "# ---------------------------------------------------------------------------"
} >> "$NEW/cut.env"

echo "[new-cut] vendoring the BOM"
if ! bash scripts/sync_cut_bom.sh "$VERSION"; then
  echo "[new-cut] sync_cut_bom.sh FAILED -- the BOM gate will be red until this is resolved." >&2
fi

echo
echo "════════ EVERY GATE, ONE PASS ════════"
RED=0
run_gate() { # name, then command
  local name="$1"; shift
  local out rc
  out="$("$@" 2>&1)"; rc=$?
  if [ "$rc" = "0" ]; then
    printf '  \033[0;32mGREEN\033[0m  %s\n' "$name"
  else
    RED=$((RED + 1))
    printf '  \033[0;31mRED  \033[0m  %s  (rc=%s)\n' "$name" "$rc"
    printf '%s\n' "$out" | tail -6 | /usr/bin/sed 's/^/           /'
  fi
}
run_gate "cut pin is current"   bash scripts/verify_cut_pin_is_current.sh --repo "$REPO" --cut "$VERSION"
run_gate "vendored BOM fresh"   bash tests/test_cut_bom_is_fresh.sh "$VERSION"
run_gate "walk closure"         bash bin/rollforward_gate.sh --require-walk-closure --cut "$VERSION"
run_gate "rollforward pin"      bash tests/test_rollforward_registry_pin.sh

echo
if [ "$RED" = "0" ]; then
  echo "ALL GREEN. Safe to tag ${VERSION}. This script does not tag: the tag is the ship."
  exit 0
fi
echo "${RED} gate(s) RED. Every one of them is above -- there is no second round of"
echo "discovery. Fix them, re-run this, then tag."
exit 1
