#!/usr/bin/env bash
# scripts/sync_cut_bom.sh
# ============================================================================
# Bring cuts/<version>/MUST_CONTAIN.tsv over from OS003 and record what was
# taken in cuts/BOM_PIN.
#
# WHY. OS003 is PRIVATE; CM051's GITHUB_TOKEN cannot read it, so the DMG
# assembly on a hosted runner cannot fetch the BOM at cut time. The BOM has to
# be vendored, exactly like the rollforward registry -- and a copy WITHOUT a
# pin is a fork nobody declared, which is how the vendored rollforward gate
# drifted 239 lines from its source.
#
# It proves the vendored file is byte-identical to a NAMED OS003 commit. It
# does NOT prove that commit is still OS003's HEAD -- no cross-repo token
# exists. Staleness is an OPERATOR check: re-run this with --check before
# tagging. Same shape, and the same honest limit, as
# scripts/sync_rollforward_registry.sh.
#
# USAGE
#   scripts/sync_cut_bom.sh <version>            copy + rewrite cuts/BOM_PIN
#   scripts/sync_cut_bom.sh <version> --check    copy nothing, report drift
#   OS003_DIR=/path/to/OS003   override the source checkout
#
# EXIT: 0 in sync / synced   1 STALE (--check)   2 CANNOT-RUN
# ============================================================================
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${OS003_DIR:-$HOME/Documents/Projects/OS003 - Ostler Release}"
VER="${1:-}"; MODE="${2:-sync}"
RED=$'\033[31m'; GRN=$'\033[32m'; YEL=$'\033[33m'; OFF=$'\033[0m'
[[ -n "${NO_COLOR:-}" ]] && { RED=''; GRN=''; YEL=''; OFF=''; }

[[ -n "$VER" ]] || { echo "usage: $0 <version> [--check]" >&2; exit 2; }
VER="${VER#v}"
# ASK GIT, do not stat `.git`. In a git WORKTREE `.git` is a FILE, not a
# directory, so `[[ -d "$SRC/.git" ]]` refuses every worktree source. The first
# version did exactly that and all three of my controls "failed" identically
# for the wrong reason -- which is what showed it up.
git -C "$SRC" rev-parse --git-dir >/dev/null 2>&1 \
  || { printf '%sCANNOT-RUN%s no OS003 git checkout at %s\n' "$YEL" "$OFF" "$SRC" >&2; exit 2; }

# A PIN TAKEN OFF A FEATURE BRANCH NAMES A COMMIT CM051 SHOULD NOT VENDOR.
# The rollforward sync refuses this and it caught a detached worktree the same
# day; same guard here rather than a second, laxer policy.
BR="$(git -C "$SRC" rev-parse --abbrev-ref HEAD 2>/dev/null)"
if [[ "$BR" != "main" && -z "${ALLOW_STALE_SOURCE:-}" ]]; then
  printf '%sERROR%s OS003 checkout is on %s, not main. Check out main or set ALLOW_STALE_SOURCE=1 deliberately.\n' "$RED" "$OFF" "$BR" >&2
  exit 2
fi

SRC_BOM="$SRC/cuts/v${VER}/MUST_CONTAIN.tsv"
[[ -f "$SRC_BOM" ]] || { printf '%sCANNOT-RUN%s OS003 has no BOM for v%s -- write it there first (bin/bom_add.sh)\n' "$YEL" "$OFF" "$VER" >&2; exit 2; }

DST="$HERE/cuts/v${VER}/MUST_CONTAIN.tsv"
SHA="$(git -C "$SRC" rev-parse HEAD)"
NEW_HASH="$(shasum -a 256 "$SRC_BOM" | cut -d' ' -f1)"
OLD_HASH=""
[[ -f "$DST" ]] && OLD_HASH="$(shasum -a 256 "$DST" | cut -d' ' -f1)"

if [[ "$MODE" == "--check" ]]; then
  if [[ "$NEW_HASH" == "$OLD_HASH" ]]; then
    printf '%sin sync%s  v%s matches OS003 %s\n' "$GRN" "$OFF" "$VER" "${SHA:0:8}"; exit 0
  fi
  printf '%sSTALE%s  the vendored BOM for v%s differs from OS003 main @ %s\n' "$RED" "$OFF" "$VER" "${SHA:0:8}" >&2
  printf '  run: scripts/sync_cut_bom.sh v%s   and commit the result\n' "$VER" >&2
  exit 1
fi

mkdir -p "$(dirname "$DST")"
cp "$SRC_BOM" "$DST"
PIN="$HERE/cuts/BOM_PIN"
{
  printf '# cuts/BOM_PIN -- generated by scripts/sync_cut_bom.sh. DO NOT HAND EDIT.\n#\n'
  printf '# Records which OS003 commit each vendored cuts/<version>/MUST_CONTAIN.tsv\n'
  printf '# was taken from, and its hash as taken. tests/test_cut_bom_is_fresh.sh\n'
  printf '# recomputes these and goes RED on any mismatch.\n#\n'
  printf '# Proves the copy matches a NAMED commit, NOT that the commit is still\n'
  printf '# OS003 HEAD. That half is an OPERATOR check: --check before tagging.\n'
  printf 'os003_repo\tandygmassey/OS003-Ostler-Release\n'
  printf 'os003_sha\t%s\n' "$SHA"
  printf 'os003_branch\tmain\n'
  printf 'cuts/v%s/MUST_CONTAIN.tsv\t%s\n' "$VER" "$NEW_HASH"
} > "$PIN"
printf '%spinned%s v%s to OS003 main @ %s\n' "$GRN" "$OFF" "$VER" "${SHA:0:8}"
printf 'Wrote cuts/BOM_PIN. Commit it WITH the vendored BOM, never separately.\n'
